<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mammouth</string>
	</array>
	<key>name</key>
	<string>Mammouth</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#language</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment.line.number-sign.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>###[^#].*?(?:###[^
]*|###$)</string>
					<key>name</key>
					<string>comment.block.mammouth</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.mammouth</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.double.mammouth</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>string.interpolated.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>true|false|null</string>
					<key>name</key>
					<string>constant.language.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\d|0b[01]+|0o[0-7]+|0(x|X)[\da-fA-F]+|\d+\.?\d+(?:(e|E)[+-]?\d+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>storage.type.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([-+*/%=^|~!&amp;&lt;&gt;]|\.|\?)</string>
					<key>name</key>
					<string>keyword.operator.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|as|break|by|catch|case|continue|declare|delete|else|finally|for|goto|if|in|instanceof|include|isnt|loop|namespace|not|null|of|once|or|require|return|switch|then|throw|try|unless|until|use|when|while)\b</string>
					<key>name</key>
					<string>keyword.control.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(echo|print)\b</string>
					<key>name</key>
					<string>support.function.construct.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(class|clone|interface|new)\b</string>
					<key>name</key>
					<string>storage.type.mammouth</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(abstract|const|cte|final|private|protected|public|static)\b</string>
					<key>name</key>
					<string>storage.modifier.mammouth</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.mammouth</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.mammouth</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.mammouth</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(func)(\s+)(([^()&gt;+\*/ -]+)?)((\([^()]*\))?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.mammouth</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.mammouth</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(extends|implements)(\s+)(([^()&gt;+\*/ -]+)?)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mammouth</string>
	<key>uuid</key>
	<string>4341ee97-4eee-47f3-84c3-416c661e7096</string>
</dict>
</plist>
