<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mammouth</string>
	</array>
	<key>name</key>
	<string>Mammouth</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#language</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>match</key>
					<string>###[^#].*?(?:###[^
]*|###$)</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.untitled</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.double.untitled</string>
				</dict>
				<dict>
					<key>match</key>
					<string>true|false</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(0b[01]+|0o[0-7]+|0(x|X)[0-9a-fA-F]+|[0-9]*[0-9].?[0-9]+(?:(e|E)[+-]?[0-9]+)?)</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[-=]</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mammouth</string>
	<key>uuid</key>
	<string>4341ee97-4eee-47f3-84c3-416c661e7096</string>
</dict>
</plist>
