// Generated by CoffeeScript 1.7.1
(function() {
  var IdCounter, nodes;

  nodes = require('./nodes');

  exports.IdCounter = IdCounter = (function() {
    function IdCounter() {}

    IdCounter.prototype.letter = ['i', 'j', 'k', 'c', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'a', 'b', 'c', 'd', 'e', 'f', 'j', 'h'];

    IdCounter.prototype._level = 1;

    IdCounter.prototype.letterLevel = 0;

    IdCounter.prototype.generateAtLevel = function() {
      var i, r;
      r = '';
      i = 0;
      while (i < this._level) {
        r += '_';
        i++;
      }
      return r;
    };

    IdCounter.prototype.next = function() {
      if ((this.letterLevel + 1) === this.letter.length) {
        this._level++;
        return this.letterLevel = 0;
      } else {
        return this.letterLevel++;
      }
    };

    IdCounter.prototype.get = function() {
      var r;
      r = this.generateAtLevel() + this.letter[this.letterLevel];
      this.next();
      return new nodes.Identifier(r);
    };

    return IdCounter;

  })();

}).call(this);
