// Generated by CoffeeScript 1.9.3
(function() {
  var lexer, parser, yy;

  yy = require('./nodes');

  parser = require('./parser').parser;

  lexer = require('./lexer');

  parser.lexer = lexer;

  parser.yy = yy;

  module.exports = {
    VERSION: '3.0.0',
    parser: parser,
    parse: function(code) {
      return this.parser.parse(code);
    }
  };

}).call(this);
