// Generated by CoffeeScript 1.9.3
(function() {
  var Context, IndentGenerator, lexer, parser, yy;

  yy = require('./nodes');

  parser = require('./parser').parser;

  lexer = require('./lexer');

  Context = require('./context');

  IndentGenerator = require('./utils').IndentGenerator;

  parser.lexer = lexer;

  parser.yy = yy;

  module.exports = {
    VERSION: '3.0.0',
    parser: parser,
    parse: function(code) {
      return this.parser.parse(code);
    },
    compile: function(code, context) {
      var result, tree;
      tree = this.parse(code);
      return result = tree.prepare().compile({
        indent: new IndentGenerator,
        context: new Context.Context(new Context.Scope)
      });
    }
  };

}).call(this);
