// Generated by CoffeeScript 1.9.3
(function() {
  exports.errorAt = function(input, pos) {
    var i, j, ref, res;
    res = input.split("\n")[pos.row - 1];
    res += '\n';
    for (i = j = 0, ref = pos.col; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      res += '^';
    }
    return res;
  };

}).call(this);
