// Generated by CoffeeScript 1.9.3
(function() {
  var IndentGenerator, IndexGenerator, nodes;

  nodes = require('./nodes');

  exports.errorAt = function(input, pos) {
    var i, j, ref, res;
    res = input.split("\n")[pos.row - 1];
    res += '\n';
    for (i = j = 0, ref = pos.col; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      res += '^';
    }
    return res;
  };

  exports.IndentGenerator = IndentGenerator = (function() {
    function IndentGenerator(indent) {
      this.indent = indent != null ? indent : '  ';
      this.level = 0;
    }

    IndentGenerator.prototype.get = function(num) {
      var i, j, ref, res;
      if (num == null) {
        num = this.level;
      }
      res = '';
      for (i = j = 0, ref = num; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        res += this.indent;
      }
      return res;
    };

    IndentGenerator.prototype.up = function() {
      return this.level++;
    };

    IndentGenerator.prototype.down = function() {
      return this.level--;
    };

    return IndentGenerator;

  })();

  exports.IndexGenerator = IndexGenerator = (function() {
    function IndexGenerator() {}

    IndexGenerator.prototype.letter = ['i', 'j', 'k', 'c', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'a', 'b', 'c', 'd', 'e', 'f', 'j', 'h'];

    IndexGenerator.prototype._level = 1;

    IndexGenerator.prototype.letterLevel = 0;

    IndexGenerator.prototype.generateAtLevel = function() {
      var i, r;
      r = '';
      i = 0;
      while (i < this._level) {
        r += '_';
        i++;
      }
      return r;
    };

    IndexGenerator.prototype.next = function() {
      if ((this.letterLevel + 1) === this.letter.length) {
        this._level++;
        return this.letterLevel = 0;
      } else {
        return this.letterLevel++;
      }
    };

    IndexGenerator.prototype.get = function() {
      var r;
      r = this.generateAtLevel() + this.letter[this.letterLevel];
      this.next();
      return new nodes.Identifier(r);
    };

    return IndexGenerator;

  })();

}).call(this);
