// Generated by CoffeeScript 1.10.0
(function() {
  var IndentGenerator, nodes;

  nodes = require('./nodes');

  exports.errorAt = function(input, pos) {
    var i, j, ref, res;
    res = input.split("\n")[pos.row - 1];
    res += '\n';
    for (i = j = 0, ref = pos.col; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      res += '^';
    }
    return res;
  };

  exports.IndentGenerator = IndentGenerator = (function() {
    function IndentGenerator(indent) {
      this.indent = indent != null ? indent : '  ';
      this.level = 0;
    }

    IndentGenerator.prototype.get = function(num) {
      var i, j, ref, res;
      if (num == null) {
        num = this.level;
      }
      res = '';
      for (i = j = 0, ref = num; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        res += this.indent;
      }
      return res;
    };

    IndentGenerator.prototype.up = function() {
      return this.level++;
    };

    IndentGenerator.prototype.down = function() {
      return this.level--;
    };

    return IndentGenerator;

  })();

}).call(this);
