{Name} = require './context'

exports.Initialize = (context) ->
    for name, type of PHPPredefined
        context.push new Name name, type

#    Precontext Addition todo list:
#    [/] Affecting PHP's Behaviour
#        [x] APC
#        [ ] APD
#        [ ] bcompiler
#        [ ] BLENC
#        [x] Error Handling
#        [ ] htscanner
#        [ ] inclued
#        [ ] Memtrack
#        [ ] OPcache
#        [ ] Output Control
#        [x] PHP Options/Info
#        [ ] runkit
#        [ ] scream
#        [ ] uopz
#        [ ] Weakref
#        [ ] WinCache
#        [ ] Xhprof
#    [ ] Audio Formats Manipulation
#        [ ] ID3
#        [ ] KTaglib
#        [ ] oggvorbis
#        [ ] OpenAL
#    [ ] Authentication Services
#        [ ] KADM5
#        [ ] Radius
#    [ ] Command Line Specific Extensions
#        [ ] Ncurses
#        [ ] Newt
#        [ ] Readline
#    [x] Compression and Archive Extensions
#        [x] Bzip2
#        [x] LZF
#        [x] Phar
#        [x] Rar
#        [x] Zip
#        [x] Zlib
#    [ ] Credit Card Processing
#        [ ] MCVE
#        [ ] SPPLUS
#    [x] Cryptography Extensions
#        [x] Crack
#        [x] Hash
#        [x] Mcrypt
#        [x] Mhash
#        [x] OpenSSL
#        [x] Password Hashing
#    [ ] Database Extensions
#        [ ] Abstraction Layers
#            [ ] DBA
#            [ ] dbx
#            [ ] ODBC
#            [ ] PDO
#        [ ] Vendor Specific Database Extensions
#            [ ] CUBRID
#            [ ] DB++
#            [ ] dBase
#            [ ] filePro
#            [ ] Firebird/InterBase
#            [ ] FrontBase
#            [ ] IBM DB2
#            [ ] Informix
#            [ ] Ingres
#            [ ] MaxDB
#            [ ] Mongo
#            [ ] MongoDB
#            [ ] mSQL
#            [ ] Mssql
#            [ ] MySQL
#            [ ] OCI8
#            [ ] Paradox
#            [ ] PostgreSQL
#            [ ] SQLite
#            [ ] SQLite3
#            [ ] SQLSRV
#            [ ] Sybase
#            [ ] tokyo_tyrant
#    [x] Date and Time Related Extensions
#        [x] Calendar
#        [x] Date/Time
#        [x] HRTime
#    [x] File System Related Extensions
#        [x] Direct IO
#        [x] Directories
#        [x] Fileinfo
#        [x] Filesystem
#        [x] Inotify
#        [x] Mimetype
#        [x] Proctitle
#        [x] xattr
#        [x] xdiff
#    [ ] Human Language and Characonstr Encoding Support
#        [ ] Enchant
#        [ ] FriBiDi
#        [ ] Gender
#        [ ] Gettext
#        [ ] iconv
#        [ ] intl
#        [ ] Multibyte String
#        [ ] Pspell
#        [ ] Recode
#    [x] Image Processing and Generation
#        [x] Cairo
#        [x] Exif
#        [x] GD
#        [x] Gmagick
#        [x] ImageMagick
#    [x] Mail Related Extensions
#        [x] Cyrus
#        [x] IMAP
#        [x] Mail
#        [x] Mailparse
#        [x] vpopmail
#    [/] Mathematical Extensions
#        [ ] BC Math
#        [ ] GMP
#        [ ] Lapack
#        [x] Math
#        [ ] Statistics
#        [ ] Trader
#    [ ] Non-Text MIME Output
#        [ ] FDF
#        [ ] GnuPG
#        [ ] haru
#        [ ] Ming
#        [ ] PDF
#        [ ] PS
#        [ ] RPM Reader
#        [ ] SWF
#    [ ] Process Control Extensions
#        [ ] Eio
#        [ ] Ev
#        [ ] Expect
#        [ ] Libevent
#        [ ] PCNTL
#        [ ] POSIX
#        [ ] Program execution
#        [ ] pthreads
#        [ ] Semaphore
#        [ ] Shared Memory
#        [ ] Sync
#    [/] Other Basic Extensions
#        [x] GeoIP
#        [ ] FANN
#        [x] JSON
#        [ ] Judy
#        [ ] Lua
#        [ ] Misc.
#        [ ] Parsekit
#        [ ] SPL
#        [ ] SPL Types
#        [ ] Streams
#        [ ] Tidy
#        [ ] Tokenizer
#        [x] URLs
#        [ ] V8js
#        [x] Yaml
#        [ ] Yaf
#        [ ] Taint
#    [/] Other Services
#        [ ] chdb
#        [x] cURL
#        [ ] Event
#        [ ] FAM
#        [x] FTP
#        [ ] Gearman
#        [ ] Gopher
#        [ ] Gupnp
#        [x] HTTP
#        [ ] Hyperwave
#        [ ] Hyperwave API
#        [ ] Java
#        [ ] LDAP
#        [ ] Lotus Notes
#        [ ] Memcache
#        [ ] Memcached
#        [ ] mqseries
#        [ ] Network
#        [ ] RRD
#        [ ] SAM
#        [ ] SNMP
#        [x] Sockets
#        [ ] SSH2
#        [ ] Stomp
#        [ ] SVM
#        [ ] SVN
#        [x] TCP
#        [ ] Varnish
#        [ ] YAZ
#        [ ] YP/NIS
#        [ ] 0MQ messaging
#    [ ] Search Engine Extensions
#        [ ] mnoGoSearch
#        [ ] Solr
#        [ ] Sphinx
#        [ ] Swish
#    [ ] Server Specific Extensions
#        [ ] Apache
#        [ ] FastCGI Process Manager
#        [ ] IIS
#        [ ] NSAPI
#    [ ] Session Extensions
#        [ ] Msession
#        [ ] Sessions
#        [ ] Session PgSQL
#    [x] Text Processing
#        [x] BBCode
#        [x] PCRE
#        [x] POSIX Regex
#        [x] ssdeep
#        [x] Strings
#    [x] Variable and Type Related Extensions
#        [x] Arrays
#        [x] Classes/Objects
#        [x] Classkit
#        [x] Ctype
#        [x] Filter
#        [x] Function Handling
#        [x] Object Aggregation
#        [x] Quickhash
#        [x] Reflection
#        [x] Variable handling
#    [ ] Web Services
#        [ ] OAuth
#        [ ] SCA
#        [ ] SOAP
#        [ ] Yar
#        [ ] XML-RPC
#    [ ] Windows Only Extensions
#        [ ] .NET
#        [ ] COM
#        [ ] W32api
#        [ ] win32ps
#        [ ] win32service
#    [ ] XML Manipulation
#        [ ] DOM
#        [ ] libxml
#        [ ] qtdom
#        [ ] SDO
#        [ ] SDO-DAS-Relational
#        [ ] SDO DAS XML
#        [ ] SimpleXML
#        [ ] WDDX
#        [ ] XMLDiff
#        [ ] XML Parser
#        [ ] XMLReader
#        [ ] XMLWriter
#        [ ] XSL
#        [ ] XSLT (PHP 4)

PHPPredefined = {
    ### Mammouth function ###
    'mammouth': 'function'


    ### Variable and Type Related Extensions ###

    # Function handling
    # Function handling Functions
    'call_​user_​func_​array': 'function'
    'call_user_func': 'function'
    'create_function': 'function'
    'forward_static_call_array': 'function'
    'forward_static_call': 'function'
    'func_get_arg': 'function'
    'func_get_args': 'function'
    'func_num_args': 'function'
    'function_exists': 'function'
    'get_defined_functions': 'function'
    'register_shutdown_function': 'function'
    'register_tick_function': 'function'
    'unregister_tick_function': 'function'

    # Arrays
    # Array Constants
    'CASE_LOWER': 'const'
    'CASE_UPPER': 'const'
    'SORT_ASC': 'const'
    'SORT_DESC': 'const'
    'SORT_REGULAR': 'const'
    'SORT_NUMERIC': 'const'
    'SORT_STRING': 'const'
    'SORT_LOCALE_STRING': 'const'
    'SORT_NATURAL': 'const'
    'SORT_FLAG_CASE': 'const'
    'COUNT_NORMAL': 'const'
    'COUNT_RECURSIVE': 'const'
    'EXTR_OVERWRITE': 'const'
    'EXTR_SKIP': 'const'
    'EXTR_PREFIX_SAME': 'const'
    'EXTR_PREFIX_ALL': 'const'
    'EXTR_PREFIX_INVALID': 'const'
    'EXTR_PREFIX_IF_EXISTS': 'const'
    'EXTR_IF_EXISTS': 'const'
    'EXTR_REFS': 'const'
    # Array functions
    'array_change_key_case': 'function'
    'array_chunk': 'function'
    'array_column': 'function'
    'array_combine': 'function'
    'array_count_values': 'function'
    'array_diff_assoc': 'function'
    'array_diff_key': 'function'
    'array_diff_uassoc': 'function'
    'array_diff_ukey': 'function'
    'array_diff': 'function'
    'array_fill_keys': 'function'
    'array_fill': 'function'
    'array_filter': 'function'
    'array_flip': 'function'
    'array_intersect_assoc': 'function'
    'array_intersect_key': 'function'
    'array_intersect_uassoc': 'function'
    'array_intersect_ukey': 'function'
    'array_intersect': 'function'
    'array_key_exists': 'function'
    'array_keys': 'function'
    'array_map': 'function'
    'array_merge_recursive': 'function'
    'array_merge': 'function'
    'array_multisort': 'function'
    'array_pad': 'function'
    'array_pop': 'function'
    'array_product': 'function'
    'array_push': 'function'
    'array_rand': 'function'
    'array_reduce': 'function'
    'array_replace_recursive': 'function'
    'array_replace': 'function'
    'array_reverse': 'function'
    'array_search': 'function'
    'array_shift': 'function'
    'array_slice': 'function'
    'array_splice': 'function'
    'array_sum': 'function'
    'array_udiff_assoc': 'function'
    'array_udiff_uassoc': 'function'
    'array_udiff': 'function'
    'array_uintersect_assoc': 'function'
    'array_uintersect_uassoc': 'function'
    'array_uintersect': 'function'
    'array_unique': 'function'
    'array_unshift': 'function'
    'array_values': 'function'
    'array_walk_recursive': 'function'
    'array_walk': 'function'
    'array': 'function'
    'arsort': 'function'
    'asort': 'function'
    'compact': 'function'
    'count': 'function'
    'current': 'function'
    'each': 'function'
    'end': 'function'
    'extract': 'function'
    'in_array': 'function'
    'key_exists': 'function'
    'key': 'function'
    'krsort': 'function'
    'ksort': 'function'
    'list': 'function'
    'natcasesort': 'function'
    'natsort': 'function'
    'next': 'function'
    'pos': 'function'
    'prev': 'function'
    'range': 'function'
    'reset': 'function'
    'rsort': 'function'
    'shuffle': 'function'
    'sizeof': 'function'
    'sort': 'function'
    'uasort': 'function'
    'uksort': 'function'
    'usort': 'function'


    # Objects/classes
    # Objects function
    '__autoload': 'function'
    'call_user_method_array': 'function'
    'call_user_method': 'function'
    'class_alias': 'function'
    'class_exists': 'function'
    'get_called_class': 'function'
    'get_class_methods': 'function'
    'get_class_vars': 'function'
    'get_class': 'function'
    'get_declared_classes': 'function'
    'get_declared_interfaces': 'function'
    'get_declared_traits': 'function'
    'get_object_vars': 'function'
    'get_parent_class': 'function'
    'interface_exists': 'function'
    'is_a': 'function'
    'is_subclass_of': 'function'
    'method_exists': 'function'
    'property_exists': 'function'
    'trait_exists': 'function'


    # Classkit
    # Classkit Constants
    'CLASSKIT_ACC_PRIVATE': 'const'
    'CLASSKIT_ACC_PROTEconstD': 'const'
    'CLASSKIT_ACC_PUBLIC': 'const'
    # Classkit Functions
    'classkit_import': 'function'
    'classkit_method_add': 'function'
    'classkit_method_copy': 'function'
    'classkit_method_redefine': 'function'
    'classkit_method_remove': 'function'
    'classkit_method_rename': 'function'


    # Ctype
    # Ctype functions
    'ctype_alnum': 'function'
    'ctype_alpha': 'function'
    'ctype_cntrl': 'function'
    'ctype_digit': 'function'
    'ctype_graph': 'function'
    'ctype_lower': 'function'
    'ctype_print': 'function'
    'ctype_punct': 'function'
    'ctype_space': 'function'
    'ctype_upper': 'function'
    'ctype_xdigit': 'function'


    # Data Filtering
    # Data Filtering Constants  
    'INPUT_POST': 'const'
    'INPUT_GET': 'const'
    'INPUT_COOKIE': 'const'
    'INPUT_ENV': 'const'
    'INPUT_SERVER': 'const'
    'INPUT_SESSION': 'const'
    'INPUT_REQUEST': 'const'
    'FILTER_FLAG_NONE': 'const'
    'FILTER_REQUIRE_SCALAR': 'const'
    'FILTER_REQUIRE_ARRAY': 'const'
    'FILTER_FORCE_ARRAY': 'const'
    'FILTER_NULL_ON_FAILURE': 'const'
    'FILTER_VALIDATE_INT': 'const'
    'FILTER_VALIDATE_BOOLEAN': 'const'
    'FILTER_VALIDATE_FLOAT': 'const'
    'FILTER_VALIDATE_REGEXP': 'const'
    'FILTER_VALIDATE_URL': 'const'
    'FILTER_VALIDATE_EMAIL': 'const'
    'FILTER_VALIDATE_IP': 'const'
    'FILTER_DEFAULT': 'const'
    'FILTER_UNSAFE_RAW': 'const'
    'FILTER_SANITIZE_STRING': 'const'
    'FILTER_SANITIZE_STRIPPED': 'const'
    'FILTER_SANITIZE_ENCODED': 'const'
    'FILTER_SANITIZE_SPECIAL_CHARS': 'const'
    'FILTER_SANITIZE_EMAIL': 'const'
    'FILTER_SANITIZE_URL': 'const'
    'FILTER_SANITIZE_NUMBER_INT': 'const'
    'FILTER_SANITIZE_NUMBER_FLOAT': 'const'
    'FILTER_SANITIZE_MAGIC_QUOTES': 'const'
    'FILTER_CALLBACK': 'const'
    'FILTER_FLAG_ALLOW_OCTAL': 'const'
    'FILTER_FLAG_ALLOW_HEX': 'const'
    'FILTER_FLAG_STRIP_LOW': 'const'
    'FILTER_FLAG_STRIP_HIGH': 'const'
    'FILTER_FLAG_ENCODE_LOW': 'const'
    'FILTER_FLAG_ENCODE_HIGH': 'const'
    'FILTER_FLAG_ENCODE_AMP': 'const'
    'FILTER_FLAG_NO_ENCODE_QUOTES': 'const'
    'FILTER_FLAG_EMPTY_STRING_NULL': 'const'
    'FILTER_FLAG_ALLOW_FRACTION': 'const'
    'FILTER_FLAG_ALLOW_THOUSAND': 'const'
    'FILTER_FLAG_ALLOW_SCIENTIFIC': 'const'
    'FILTER_FLAG_PATH_REQUIRED': 'const'
    'FILTER_FLAG_QUERY_REQUIRED': 'const'
    'FILTER_FLAG_IPV4': 'const'
    'FILTER_FLAG_IPV6': 'const'
    'FILTER_FLAG_NO_RES_RANGE': 'const'
    'FILTER_FLAG_NO_PRIV_RANGE': 'const'
    # Data filtering functions
    'filter_has_var': 'function'
    'filter_id': 'function'
    'filter_input_array': 'function'
    'filter_input': 'function'
    'filter_list': 'function'
    'filter_var_array': 'function'
    'filter_var': 'function'


    # Object Aggregation/Composition
    # Object Aggregation functions
    'aggregate_infoh': 'function'
    'aggregate_methods_by_list': 'function'
    'aggregate_methods_by_regexp': 'function'
    'aggregate_methods': 'function'
    'aggregate_properties_by_list': 'function'
    'aggregate_properties_by_regexp': 'function'
    'aggregate_properties': 'function'
    'aggregate': 'function'
    'aggregation_info': 'function'
    'deaggregate': 'function'


    # Quickhash
    # Quickhash classes
    'QuickHashIntSet': 'class'
    'QuickHashIntHash': 'class'
    'QuickHashStringIntHash': 'class'
    'QuickHashIntStringHash': 'class'


    # Reflection
    # Reflection classes
    'Reflection': 'class'
    'ReflectionClass': 'class'
    'ReflectionZendExtension': 'class'
    'ReflectionExtension': 'class'
    'ReflectionFunction': 'class'
    'ReflectionFunctionAbstract': 'class'
    'ReflectionMethod': 'class'
    'ReflectionObject': 'class'
    'ReflectionParameter': 'class'
    'ReflectionProperty': 'class'
    'Reflector': 'class'
    'ReflectionException': 'class'


    # Variable handling
    # Variable handling functions
    'boolval': 'function'
    'debug_zval_dump': 'function'
    'doubleval': 'function'
    'empty': 'function'
    'floatval': 'function'
    'get_defined_vars': 'function'
    'get_resource_type': 'function'
    'gettype': 'function'
    'import_request_variables': 'function'
    'intval': 'function'
    'is_array': 'function'
    'is_bool': 'function'
    'is_callable': 'function'
    'is_double': 'function'
    'is_float': 'function'
    'is_int': 'function'
    'is_integer': 'function'
    'is_long': 'function'
    'is_null': 'function'
    'is_numeric': 'function'
    'is_object': 'function'
    'is_real': 'function'
    'is_resource': 'function'
    'is_scalar': 'function'
    'is_string': 'function'
    'isset': 'function'
    'print_r': 'function'
    'serialize': 'function'
    'settype': 'function'
    'strval': 'function'
    'unserialize': 'function'
    'unset': 'function'
    'var_dump': 'function'
    'var_export': 'function'


    ### Date and Time Related Extensions ###

    # Calendar
    # Calendar constants
    'CAL_GREGORIAN': 'const'
    'CAL_JULIAN': 'const'
    'CAL_JEWISH': 'const'
    'CAL_FRENCH': 'const'
    'CAL_NUM_CALS': 'const'
    'CAL_DOW_DAYNO': 'const'
    'CAL_DOW_SHORT': 'const'
    'CAL_DOW_LONG': 'const'
    'CAL_MONTH_GREGORIAN_SHORT': 'const'
    'CAL_MONTH_GREGORIAN_LONG': 'const'
    'CAL_MONTH_JULIAN_SHORT': 'const'
    'CAL_MONTH_JULIAN_LONG': 'const'
    'CAL_MONTH_JEWISH': 'const'
    'CAL_MONTH_FRENCH': 'const'
    'CAL_EASTER_DEFAULT': 'const'
    'CAL_EASTER_ROMAN': 'const'
    'CAL_EASTER_ALWAYS_GREGORIAN': 'const'
    'CAL_EASTER_ALWAYS_JULIAN': 'const'
    'CAL_JEWISH_ADD_ALAFIM_GERESH': 'const'
    'CAL_JEWISH_ADD_ALAFIM': 'const'
    'CAL_JEWISH_ADD_GERESHAYIM  ': 'const'
    # Calendar function
    'cal_days_in_month': 'function'
    'cal_from_jd': 'function'
    'cal_info': 'function'
    'cal_to_jd': 'function'
    'easter_date': 'function'
    'easter_days': 'function'
    'frenchtojd': 'function'
    'gregoriantojd': 'function'
    'jddayofweek': 'function'
    'jdmonthname': 'function'
    'jdtofrench': 'function'
    'jdtogregorian': 'function'
    'jdtojewish': 'function'
    'jdtojulian': 'function'
    'jdtounix': 'function'
    'jewishtojd': 'function'
    'juliantojd': 'function'
    'unixtojd': 'function'

    # Date/Time
    # Date/Time classes
    'DateTime': 'class'
    'DateTimeImmutable': 'class'
    'DateTimeInterface': 'class'
    'DateTimeZone': 'class'
    'DateInterval': 'class'
    'DatePeriod': 'class'
    # Date/Time constants
    'SUNFUNCS_RET_TIMESTAMP': 'const'
    'SUNFUNCS_RET_STRING': 'const'
    'SUNFUNCS_RET_DOUBLE': 'const'
    # Date/Time functions
    'checkdate': 'function'
    'date_add': 'function'
    'date_create_from_format': 'function'
    'date_create_immutable_from_format': 'function'
    'date_create_immutable': 'function'
    'date_create': 'function'
    'date_date_set': 'function'
    'date_default_timezone_get': 'function'
    'date_default_timezone_set': 'function'
    'date_diff': 'function'
    'date_format': 'function'
    'date_get_last_errors': 'function'
    'date_interval_create_from_date_string': 'function'
    'date_interval_format': 'function'
    'date_isodate_set': 'function'
    'date_modify': 'function'
    'date_offset_get': 'function'
    'date_parse_from_format': 'function'
    'date_parse': 'function'
    'date_sub': 'function'
    'date_sun_info': 'function'
    'date_sunrise': 'function'
    'date_sunset': 'function'
    'date_time_set': 'function'
    'date_timestamp_get': 'function'
    'date_timestamp_set': 'function'
    'date_timezone_get': 'function'
    'date_timezone_set': 'function'
    'date': 'function'
    'getdate': 'function'
    'gettimeofday': 'function'
    'gmdate': 'function'
    'gmmktime': 'function'
    'gmstrftime': 'function'
    'idate': 'function'
    'localtime': 'function'
    'microtime': 'function'
    'mktime': 'function'
    'strftime': 'function'
    'strptime': 'function'
    'strtotime': 'function'
    'time': 'function'
    'timezone_abbreviations_list': 'function'
    'timezone_identifiers_list': 'function'
    'timezone_location_get': 'function'
    'timezone_name_from_abbr': 'function'
    'timezone_name_get': 'function'
    'timezone_offset_get': 'function'
    'timezone_open': 'function'
    'timezone_transitions_get': 'function'
    'timezone_version_get': 'function'


    ### File System Related Extensions ###

    # Direct IO
    # Direct IO constants
    'F_DUPFD': 'const'
    'F_GETFD': 'const'
    'F_GETFL': 'const'
    'F_GETLK': 'const'
    'F_GETOWN': 'const'
    'F_RDLCK': 'const'
    'F_SETFL': 'const'
    'F_SETLK': 'const'
    'F_SETLKW': 'const'
    'F_SETOWN': 'const'
    'F_UNLCK': 'const'
    'F_WRLCK': 'const'
    'O_APPEND': 'const'
    'O_ASYNC': 'const'
    'O_CREAT': 'const'
    'O_EXCL': 'const'
    'O_NDELAY': 'const'
    'O_NOCTTY': 'const'
    'O_NONBLOCK': 'const'
    'O_RDONLY': 'const'
    'O_RDWR': 'const'
    'O_SYNC': 'const'
    'O_TRUNC': 'const'
    'O_WRONLY': 'const'
    'S_IRGRP': 'const'
    'S_IROTH': 'const'
    'S_IRUSR': 'const'
    'S_IRWXG': 'const'
    'S_IRWXO': 'const'
    'S_IRWXU': 'const'
    'S_IWGRP': 'const'
    'S_IWOTH': 'const'
    'S_IWUSR': 'const'
    'S_IXGRP': 'const'
    'S_IXOTH': 'const'
    'S_IXUSR': 'const'
    # Direct IO functions
    'dio_close': 'function'
    'dio_fcntl': 'function'
    'dio_open': 'function'
    'dio_read': 'function'
    'dio_seek': 'function'
    'dio_stat': 'function'
    'dio_tcsetattr': 'function'
    'dio_truncate': 'function'
    'dio_write': 'function'

    # Directories 
    # Directories constants
    'DIRECTORY_SEPARATOR': 'const'
    'PATH_SEPARATOR': 'const'
    'SCANDIR_SORT_ASCENDING': 'const'
    'SCANDIR_SORT_DESCENDING': 'const'
    'SCANDIR_SORT_NONE': 'const'
    # Directories classes
    "Directory": "class"
    # Directories functions
    'chdir': 'function'
    'chroot': 'function'
    'closedir': 'function'
    'dir': 'function'
    'getcwd': 'function'
    'opendir': 'function'
    'readdir': 'function'
    'rewinddir': 'function'
    'scandir': 'function'

    # File Information
    # File Information constants
    'FILEINFO_NONE': 'const'
    'FILEINFO_SYMLINK': 'const'
    'FILEINFO_MIME_TYPE': 'const'
    'FILEINFO_MIME_ENCODING': 'const'
    'FILEINFO_MIME': 'const'
    'FILEINFO_COMPRESS': 'const'
    'FILEINFO_DEVICES': 'const'
    'FILEINFO_CONTINUE': 'const'
    'FILEINFO_PRESERVE_ATIME': 'const'
    'FILEINFO_RAW': 'const'
    # File Information functions
    'finfo_close': 'function'
    'finfo_file': 'function'
    'finfo_open': 'function'
    'finfo_set_flags': 'function'
    'mime_content_type': 'function'

    # Filesystem
    # Filesystem constants
    'SEEK_SET': 'const'
    'SEEK_CUR': 'const'
    'SEEK_END': 'const'
    'LOCK_SH': 'const'
    'LOCK_EX': 'const'
    'LOCK_UN': 'const'
    'LOCK_NB': 'const'
    'GLOB_BRACE': 'const'
    'GLOB_ONLYDIR': 'const'
    'GLOB_MARK': 'const'
    'GLOB_NOSORT': 'const'
    'GLOB_NOCHECK': 'const'
    'GLOB_NOESCAPE': 'const'
    'GLOB_AVAILABLE_FLAGS': 'const'
    'PATHINFO_DIRNAME': 'const'
    'PATHINFO_BASENAME': 'const'
    'PATHINFO_EXTENSION': 'const'
    'PATHINFO_FILENAME': 'const'
    'FILE_USE_INCLUDE_PATH': 'const'
    'FILE_NO_DEFAULT_CONTEXT': 'const'
    'FILE_APPEND': 'const'
    'FILE_IGNORE_NEW_LINES': 'const'
    'FILE_SKIP_EMPTY_LINES': 'const'
    'FILE_BINARY': 'const'
    'FILE_TEXT': 'const'
    'INI_SCANNER_NORMAL': 'const'
    'INI_SCANNER_RAW': 'const'
    'FNM_NOESCAPE': 'const'
    'FNM_PATHNAME': 'const'
    'FNM_PERIOD': 'const'
    'FNM_CASEFOLD': 'const'
    # Filesystem functions
    'basename': 'function'
    'chgrp': 'function'
    'chmod': 'function'
    'chown': 'function'
    'clearstatcache': 'function'
    'copy': 'function'
    'delete': 'function'
    'dirname': 'function'
    'disk_free_space': 'function'
    'disk_total_space': 'function'
    'diskfreespace': 'function'
    'fclose': 'function'
    'feof': 'function'
    'fflush': 'function'
    'fgetc': 'function'
    'fgetcsv': 'function'
    'fgets': 'function'
    'fgetss': 'function'
    'file_exists': 'function'
    'file_get_contents': 'function'
    'file_put_contents': 'function'
    'file': 'function'
    'fileatime': 'function'
    'filectime': 'function'
    'filegroup': 'function'
    'fileinode': 'function'
    'filemtime': 'function'
    'fileowner': 'function'
    'fileperms': 'function'
    'filesize': 'function'
    'filetype': 'function'
    'flock': 'function'
    'fnmatch': 'function'
    'fopen': 'function'
    'fpassthru': 'function'
    'fputcsv': 'function'
    'fputs': 'function'
    'fread': 'function'
    'fscanf': 'function'
    'fseek': 'function'
    'fstat': 'function'
    'ftell': 'function'
    'ftruncate': 'function'
    'fwrite': 'function'
    'glob': 'function'
    'is_dir': 'function'
    'is_executable': 'function'
    'is_file': 'function'
    'is_link': 'function'
    'is_readable': 'function'
    'is_uploaded_file': 'function'
    'is_writable': 'function'
    'is_writeable': 'function'
    'lchgrp': 'function'
    'lchown': 'function'
    'link': 'function'
    'linkinfo': 'function'
    'lstat': 'function'
    'mkdir': 'function'
    'move_uploaded_file': 'function'
    'parse_ini_file': 'function'
    'parse_ini_string': 'function'
    'pathinfo': 'function'
    'pclose': 'function'
    'popen': 'function'
    'readfile': 'function'
    'readlink': 'function'
    'realpath_cache_get': 'function'
    'realpath_cache_size': 'function'
    'realpath': 'function'
    'rename': 'function'
    'rewind': 'function'
    'rmdir': 'function'
    'set_file_buffer': 'function'
    'stat': 'function'
    'symlink': 'function'
    'tempnam': 'function'
    'tmpfile': 'function'
    'touch': 'function'
    'umask': 'function'
    'unlink': 'function'

    # Inotify
    # Inotify constants
    'IN_ACCESS': 'const'
    'IN_MODIFY': 'const'
    'IN_ATTRIB': 'const'
    'IN_CLOSE_WRITE': 'const'
    'IN_CLOSE_NOWRITE': 'const'
    'IN_OPEN': 'const'
    'IN_MOVED_TO': 'const'
    'IN_MOVED_FROM': 'const'
    'IN_CREATE': 'const'
    'IN_DELETE': 'const'
    'IN_DELETE_SELF': 'const'
    'IN_MOVE_SELF': 'const'
    'IN_CLOSE': 'const'
    'IN_MOVE': 'const'
    'IN_ALL_EVENTS': 'const'
    'IN_UNMOUNT': 'const'
    'IN_Q_OVERFLOW': 'const'
    'IN_IGNORED': 'const'
    'IN_ISDIR': 'const'
    'IN_ONLYDIR': 'const'
    'IN_DONT_FOLLOW': 'const'
    'IN_MASK_ADD': 'const'
    'IN_ONESHOT': 'const'
    # Inotify functions
    'inotify_add_watch': 'function'
    'inotify_init': 'function'
    'inotify_queue_len': 'function'
    'inotify_read': 'function'
    'inotify_rm_watch': 'function'

    # Proctitle
    # Proctitle functions
    'setproctitle': 'function'
    'setthreadtitle': 'function'

    # xattr
    # xattr constants
    'XATTR_ROOT': 'const'
    'XATTR_DONTFOLLOW': 'const'
    'XATTR_CREATE': 'const'
    'XATTR_REPLACE': 'const'
    # xattr functions
    'xattr_get': 'function'
    'xattr_list': 'function'
    'xattr_remove': 'function'
    'xattr_set': 'function'
    'xattr_supported': 'function'

    # xdiff
    # xdiff constants
    'XDIFF_PATCH_NORMAL': 'const'
    'XDIFF_PATCH_REVERSE': 'const'
    # xdiff functions
    'xdiff_file_bdiff_size': 'function'
    'xdiff_file_bdiff': 'function'
    'xdiff_file_bpatch': 'function'
    'xdiff_file_diff_binary': 'function'
    'xdiff_file_diff': 'function'
    'xdiff_file_merge3': 'function'
    'xdiff_file_patch_binary': 'function'
    'xdiff_file_patch': 'function'
    'xdiff_file_rabdiff': 'function'
    'xdiff_string_bdiff_size': 'function'
    'xdiff_string_bdiff': 'function'
    'xdiff_string_bpatch': 'function'
    'xdiff_string_diff_binary': 'function'
    'xdiff_string_diff': 'function'
    'xdiff_string_merge3': 'function'
    'xdiff_string_patch_binary': 'function'
    'xdiff_string_patch': 'function'
    'xdiff_string_rabdiff': 'function'


    ### Image Processing and Generation ###

    # Cairo
    # Cairo constants
    'CAIRO_STATUS_SUCCESS': 'const'
    'CAIRO_STATUS_NO_MEMORY': 'const'
    'CAIRO_STATUS_INVALID_RESTORE': 'const'
    'CAIRO_STATUS_INVALID_POP_GROUP': 'const'
    'CAIRO_STATUS_NO_CURRENT_POINT': 'const'
    'CAIRO_STATUS_INVALID_MATRIX': 'const'
    'CAIRO_STATUS_INVALID_STATUS': 'const'
    'CAIRO_STATUS_NULL_POINTER': 'const'
    'CAIRO_STATUS_INVALID_STRING': 'const'
    'CAIRO_STATUS_INVALID_PATH_DATA': 'const'
    'CAIRO_STATUS_READ_ERROR': 'const'
    'CAIRO_STATUS_WRITE_ERROR': 'const'
    'CAIRO_STATUS_SURFACE_FINISHED': 'const'
    'CAIRO_STATUS_SURFACE_TYPE_MISMATCH': 'const'
    'CAIRO_STATUS_PATTERN_TYPE_MISMATCH': 'const'
    'CAIRO_STATUS_INVALID_CONTENT': 'const'
    'CAIRO_STATUS_INVALID_FORMAT': 'const'
    'CAIRO_STATUS_INVALID_VISUAL': 'const'
    'CAIRO_STATUS_FILE_NOT_FOUND': 'const'
    'CAIRO_STATUS_INVALID_DASH': 'const'
    'CAIRO_STATUS_INVALID_DSC_COMMENT': 'const'
    'CAIRO_STATUS_INVALID_INDEX': 'const'
    'CAIRO_STATUS_CLIP_NOT_REPRESENTABLE': 'const'
    'CAIRO_STATUS_TEMP_FILE_ERROR': 'const'
    'CAIRO_STATUS_INVALID_STRIDE': 'const'
    'CAIRO_ANTIALIAS_DEFAULT': 'const'
    'CAIRO_ANTIALIAS_NONE': 'const'
    'CAIRO_ANTIALIAS_GRAY': 'const'
    'CAIRO_ANTIALIAS_SUBPIXEL': 'const'
    'CAIRO_SUBPIXEL_ORDER_DEFAULT': 'const'
    'CAIRO_SUBPIXEL_ORDER_RGB': 'const'
    'CAIRO_SUBPIXEL_ORDER_BGR': 'const'
    'CAIRO_SUBPIXEL_ORDER_VRGB': 'const'
    'CAIRO_SUBPIXEL_ORDER_VBGR': 'const'
    'CAIRO_FILL_RULE_WINDING': 'const'
    'CAIRO_FILL_RULE_EVEN_ODD': 'const'
    'CAIRO_LINE_CAP_BUTT': 'const'
    'CAIRO_LINE_CAP_ROUND': 'const'
    'CAIRO_LINE_CAP_SQUARE': 'const'
    'CAIRO_LINE_JOIN_MITER': 'const'
    'CAIRO_LINE_JOIN_ROUND': 'const'
    'CAIRO_LINE_JOIN_BEVEL': 'const'
    'CAIRO_OPERATOR_CLEAR': 'const'
    'CAIRO_OPERATOR_SOURCE': 'const'
    'CAIRO_OPERATOR_OVER': 'const'
    'CAIRO_OPERATOR_IN': 'const'
    'CAIRO_OPERATOR_OUT': 'const'
    'CAIRO_OPERATOR_ATOP': 'const'
    'CAIRO_OPERATOR_DEST': 'const'
    'CAIRO_OPERATOR_DEST_OVER': 'const'
    'CAIRO_OPERATOR_DEST_IN': 'const'
    'CAIRO_OPERATOR_DEST_OUT': 'const'
    'CAIRO_OPERATOR_DEST_ATOP': 'const'
    'CAIRO_OPERATOR_XOR': 'const'
    'CAIRO_OPERATOR_ADD': 'const'
    'CAIRO_OPERATOR_SATURATE': 'const'
    'CAIRO_PATTERN_TYPE_SOLID': 'const'
    'CAIRO_PATTERN_TYPE_SURFACE': 'const'
    'CAIRO_PATTERN_TYPE_LINEAR': 'const'
    'CAIRO_PATTERN_TYPE_RADIAL': 'const'
    'CAIRO_EXTEND_NONE': 'const'
    'CAIRO_EXTEND_REPEAT': 'const'
    'CAIRO_EXTEND_REFLECT': 'const'
    'CAIRO_EXTEND_PAD': 'const'
    'CAIRO_FILTER_FAST': 'const'
    'CAIRO_FILTER_GOOD': 'const'
    'CAIRO_FILTER_BEST': 'const'
    'CAIRO_FILTER_NEAREST': 'const'
    'CAIRO_FILTER_BILINEAR': 'const'
    'CAIRO_FILTER_GAUSSIAN': 'const'
    'CAIRO_HINT_STYLE_DEFAULT': 'const'
    'CAIRO_HINT_STYLE_NONE': 'const'
    'CAIRO_HINT_STYLE_SLIGHT': 'const'
    'CAIRO_HINT_STYLE_MEDIUM': 'const'
    'CAIRO_HINT_STYLE_FULL': 'const'
    'CAIRO_HINT_METRICS_DEFAULT': 'const'
    'CAIRO_HINT_METRICS_OFF': 'const'
    'CAIRO_HINT_METRICS_ON': 'const'
    'CAIRO_FONT_TYPE_TOY': 'const'
    'CAIRO_FONT_TYPE_FT': 'const'
    'CAIRO_FONT_TYPE_WIN32': 'const'
    'CAIRO_FONT_TYPE_QUARTZ': 'const'
    'CAIRO_FONT_SLANT_NORMAL': 'const'
    'CAIRO_FONT_SLANT_ITALIC': 'const'
    'CAIRO_FONT_SLANT_OBLIQUE': 'const'
    'CAIRO_FONT_WEIGHT_NORMAL': 'const'
    'CAIRO_FONT_WEIGHT_BOLD': 'const'
    'CAIRO_CONTENT_COLOR': 'const'
    'CAIRO_CONTENT_ALPHA': 'const'
    'CAIRO_CONTENT_COLOR_ALPHA': 'const'
    'CAIRO_SURFACE_TYPE_IMAGE': 'const'
    'CAIRO_SURFACE_TYPE_PDF': 'const'
    'CAIRO_SURFACE_TYPE_PS': 'const'
    'CAIRO_SURFACE_TYPE_XLIB': 'const'
    'CAIRO_SURFACE_TYPE_XCB': 'const'
    'CAIRO_SURFACE_TYPE_GLITZ': 'const'
    'CAIRO_SURFACE_TYPE_QUARTZ': 'const'
    'CAIRO_SURFACE_TYPE_WIN32': 'const'
    'CAIRO_SURFACE_TYPE_BEOS': 'const'
    'CAIRO_SURFACE_TYPE_DIRECTFB': 'const'
    'CAIRO_SURFACE_TYPE_SVG': 'const'
    'CAIRO_SURFACE_TYPE_OS2': 'const'
    'CAIRO_SURFACE_TYPE_WIN32_PRINTING': 'const'
    'CAIRO_SURFACE_TYPE_QUARTZ_IMAGE': 'const'
    'CAIRO_FORMAT_ARGB32': 'const'
    'CAIRO_FORMAT_RGB24': 'const'
    'CAIRO_FORMAT_A8': 'const'
    'CAIRO_FORMAT_A1': 'const'
    'CAIRO_PS_LEVEL_2': 'const'
    'CAIRO_PS_LEVEL_3': 'const'
    'CAIRO_SVG_VERSION_1_1': 'const'
    'CAIRO_SVG_VERSION_1_2': 'const'
    # Cairo functions
    'cairo_create': 'function'
    'cairo_font_face_get_type': 'function'
    'cairo_font_face_status': 'function'
    'cairo_font_options_create': 'function'
    'cairo_font_options_equal': 'function'
    'cairo_font_options_get_antialias': 'function'
    'cairo_font_options_get_hint_metrics': 'function'
    'cairo_font_options_get_hint_style': 'function'
    'cairo_font_options_get_subpixel_order': 'function'
    'cairo_font_options_hash': 'function'
    'cairo_font_options_merge': 'function'
    'cairo_font_options_set_antialias': 'function'
    'cairo_font_options_set_hint_metrics': 'function'
    'cairo_font_options_set_hint_style': 'function'
    'cairo_font_options_set_subpixel_order': 'function'
    'cairo_font_options_status': 'function'
    'cairo_format_stride_for_width': 'function'
    'cairo_image_surface_create_for_data': 'function'
    'cairo_image_surface_create_from_png': 'function'
    'cairo_image_surface_create': 'function'
    'cairo_image_surface_get_data': 'function'
    'cairo_image_surface_get_format': 'function'
    'cairo_image_surface_get_height': 'function'
    'cairo_image_surface_get_stride': 'function'
    'cairo_image_surface_get_width': 'function'
    'cairo_matrix_create_scale': 'function'
    'cairo_matrix_create_translate': 'function'
    'cairo_matrix_invert': 'function'
    'cairo_matrix_multiply': 'function'
    'cairo_matrix_rotate': 'function'
    'cairo_matrix_transform_distance': 'function'
    'cairo_matrix_transform_point': 'function'
    'cairo_matrix_translate': 'function'
    'cairo_pattern_add_color_stop_rgb': 'function'
    'cairo_pattern_add_color_stop_rgba': 'function'
    'cairo_pattern_create_for_surface': 'function'
    'cairo_pattern_create_linear': 'function'
    'cairo_pattern_create_radial': 'function'
    'cairo_pattern_create_rgb': 'function'
    'cairo_pattern_create_rgba': 'function'
    'cairo_pattern_get_color_stop_count': 'function'
    'cairo_pattern_get_color_stop_rgba': 'function'
    'cairo_pattern_get_extend': 'function'
    'cairo_pattern_get_filter': 'function'
    'cairo_pattern_get_linear_points': 'function'
    'cairo_pattern_get_matrix': 'function'
    'cairo_pattern_get_radial_circles': 'function'
    'cairo_pattern_get_rgba': 'function'
    'cairo_pattern_get_surface': 'function'
    'cairo_pattern_get_type': 'function'
    'cairo_pattern_set_extend': 'function'
    'cairo_pattern_set_filter': 'function'
    'cairo_pattern_set_matrix': 'function'
    'cairo_pattern_status': 'function'
    'cairo_pdf_surface_create': 'function'
    'cairo_pdf_surface_set_size': 'function'
    'cairo_ps_get_levels': 'function'
    'cairo_ps_level_to_string': 'function'
    'cairo_ps_surface_create': 'function'
    'cairo_ps_surface_dsc_begin_page_setup': 'function'
    'cairo_ps_surface_dsc_begin_setup': 'function'
    'cairo_ps_surface_dsc_comment': 'function'
    'cairo_ps_surface_get_eps': 'function'
    'cairo_ps_surface_restrict_to_level': 'function'
    'cairo_ps_surface_set_eps': 'function'
    'cairo_ps_surface_set_size': 'function'
    'cairo_scaled_font_create': 'function'
    'cairo_scaled_font_extents': 'function'
    'cairo_scaled_font_get_ctm': 'function'
    'cairo_scaled_font_get_font_face': 'function'
    'cairo_scaled_font_get_font_matrix': 'function'
    'cairo_scaled_font_get_font_options': 'function'
    'cairo_scaled_font_get_scale_matrix': 'function'
    'cairo_scaled_font_get_type': 'function'
    'cairo_scaled_font_glyph_extents': 'function'
    'cairo_scaled_font_status': 'function'
    'cairo_scaled_font_text_extents': 'function'
    'cairo_surface_copy_page': 'function'
    'cairo_surface_create_similar': 'function'
    'cairo_surface_finish': 'function'
    'cairo_surface_flush': 'function'
    'cairo_surface_get_content': 'function'
    'cairo_surface_get_device_offset': 'function'
    'cairo_surface_get_font_options': 'function'
    'cairo_surface_get_type': 'function'
    'cairo_surface_mark_dirty_rectangle': 'function'
    'cairo_surface_mark_dirty': 'function'
    'cairo_surface_set_device_offset': 'function'
    'cairo_surface_set_fallback_resolution': 'function'
    'cairo_surface_show_page': 'function'
    'cairo_surface_status': 'function'
    'cairo_surface_write_to_png': 'function'
    'cairo_svg_surface_create': 'function'
    'cairo_svg_surface_restrict_to_version': 'function'
    'cairo_svg_version_to_string': 'function'
    # Cairo classes
    'Cairo': 'class'
    'CairoContext': 'class'
    'CairoException': 'class'
    'CairoStatus': 'class'
    'CairoSurface': 'class'
    'CairoSvgSurface': 'class'
    'CairoImageSurface': 'class'
    'CairoPdfSurface': 'class'
    'CairoPsSurface': 'class'
    'CairoSurfaceType': 'class'
    'CairoFontFace': 'class'
    'CairoFontOptions': 'class'
    'CairoFontSlant': 'class'
    'CairoFontType': 'class'
    'CairoFontWeight': 'class'
    'CairoScaledFont': 'class'
    'CairoToyFontFace': 'class'
    'CairoPatternType': 'class'
    'CairoPattern': 'class'
    'CairoGradientPattern': 'class'
    'CairoSolidPattern': 'class'
    'CairoSurfacePattern': 'class'
    'CairoLinearGradient': 'class'
    'CairoRadialGradient': 'class'
    'CairoAntialias': 'class'
    'CairoContent': 'class'
    'CairoExtend': 'class'
    'CairoFormat': 'class'
    'CairoFillRule': 'class'
    'CairoFilter': 'class'
    'CairoHintMetrics': 'class'
    'CairoHintStyle': 'class'
    'CairoLineCap': 'class'
    'CairoLineJoin': 'class'
    'CairoMatrix': 'class'
    'CairoOperator': 'class'
    'CairoPath': 'class'
    'CairoPsLevel': 'class'
    'CairoSubpixelOrder': 'class'
    'CairoSvgVersion': 'class'

    # Exif
    # Exif constants
    'EXIF_USE_MBSTRING': 'const'
    'IMAGETYPE_GIF': 'const'
    'IMAGETYPE_JPEG': 'const'
    'IMAGETYPE_PNG': 'const'
    'IMAGETYPE_SWF': 'const'
    'IMAGETYPE_PSD': 'const'
    'IMAGETYPE_BMP': 'const'
    'IMAGETYPE_TIFF_II': 'const'
    'IMAGETYPE_TIFF_MM': 'const'
    'IMAGETYPE_JPC': 'const'
    'IMAGETYPE_JP2': 'const'
    'IMAGETYPE_JPX': 'const'
    'IMAGETYPE_JB2': 'const'
    'IMAGETYPE_SWC': 'const'
    'IMAGETYPE_IFF': 'const'
    'IMAGETYPE_WBMP': 'const'
    'IMAGETYPE_XBM': 'const'
    'IMAGETYPE_ICO': 'const'
    # Exif functions
    'exif_imagetype': 'function'
    'exif_read_data': 'function'
    'exif_tagname': 'function'
    'exif_thumbnail': 'function'
    'read_exif_data': 'function'

    # GD
    # GD constants
    'GD_VERSION': 'const'
    'GD_MAJOR_VERSION': 'const'
    'GD_MINOR_VERSION': 'const'
    'GD_RELEASE_VERSION': 'const'
    'GD_EXTRA_VERSION': 'const'
    'GD_BUNDLED': 'const'
    'IMG_GIF': 'const'
    'IMG_JPG': 'const'
    'IMG_JPEG': 'const'
    'IMG_PNG': 'const'
    'IMG_WBMP': 'const'
    'IMG_XPM': 'const'
    'IMG_COLOR_TILED': 'const'
    'IMG_COLOR_STYLED': 'const'
    'IMG_COLOR_BRUSHED': 'const'
    'IMG_COLOR_STYLEDBRUSHED': 'const'
    'IMG_COLOR_TRANSPARENT': 'const'
    'IMG_ARC_ROUNDED': 'const'
    'IMG_ARC_PIE': 'const'
    'IMG_ARC_CHORD': 'const'
    'IMG_ARC_NOFILL': 'const'
    'IMG_ARC_EDGED': 'const'
    'IMG_GD2_RAW': 'const'
    'IMG_GD2_COMPRESSED': 'const'
    'IMG_EFFECT_REPLACE': 'const'
    'IMG_EFFECT_ALPHABLEND': 'const'
    'IMG_EFFECT_NORMAL': 'const'
    'IMG_EFFECT_OVERLAY': 'const'
    'IMG_FILTER_NEGATE': 'const'
    'IMG_FILTER_GRAYSCALE': 'const'
    'IMG_FILTER_BRIGHTNESS': 'const'
    'IMG_FILTER_CONTRAST': 'const'
    'IMG_FILTER_COLORIZE': 'const'
    'IMG_FILTER_EDGEDETECT': 'const'
    'IMG_FILTER_GAUSSIAN_BLUR': 'const'
    'IMG_FILTER_SELECTIVE_BLUR': 'const'
    'IMG_FILTER_EMBOSS': 'const'
    'IMG_FILTER_MEAN_REMOVAL': 'const'
    'IMG_FILTER_SMOOTH': 'const'
    'IMG_FILTER_PIXELATE': 'const'
    'IMAGETYPE_GIF': 'const'
    'IMAGETYPE_JPEG': 'const'
    'IMAGETYPE_JPEG2000': 'const'
    'IMAGETYPE_PNG': 'const'
    'IMAGETYPE_SWF': 'const'
    'IMAGETYPE_PSD': 'const'
    'IMAGETYPE_BMP': 'const'
    'IMAGETYPE_WBMP': 'const'
    'IMAGETYPE_XBM': 'const'
    'IMAGETYPE_TIFF_II': 'const'
    'IMAGETYPE_TIFF_MM': 'const'
    'IMAGETYPE_IFF': 'const'
    'IMAGETYPE_JB2': 'const'
    'IMAGETYPE_JPC': 'const'
    'IMAGETYPE_JP2': 'const'
    'IMAGETYPE_JPX': 'const'
    'IMAGETYPE_SWC': 'const'
    'IMAGETYPE_ICO': 'const'
    'PNG_NO_FILTER': 'const'
    'PNG_FILTER_NONE': 'const'
    'PNG_FILTER_SUB': 'const'
    'PNG_FILTER_UP': 'const'
    'PNG_FILTER_AVG': 'const'
    'PNG_FILTER_PAETH': 'const'
    'PNG_ALL_FILTERS': 'const'
    'IMG_FLIP_VERTICAL': 'const'
    'IMG_FLIP_HORIZONTAL': 'const'
    'IMG_FLIP_BOTH': 'const'
    'IMG_BELL': 'const'
    'IMG_BESSEL': 'const'
    'IMG_BILINEAR_FIXED': 'const'
    'IMG_BICUBIC': 'const'
    'IMG_BICUBIC': 'const'
    'IMG_BLACKMAN': 'const'
    'IMG_BOX': 'const'
    'IMG_BSPLINE': 'const'
    'IMG_CATMULLROM': 'const'
    'IMG_GAUSSIAN': 'const'
    'IMG_GENERALIZED_CUBIC': 'const'
    'IMG_HERMITE': 'const'
    'IMG_HAMMING': 'const'
    'IMG_HANNING': 'const'
    'IMG_MITCHELL': 'const'
    'IMG_POWER': 'const'
    'IMG_QUADRATIC': 'const'
    'IMG_SINC': 'const'
    'IMG_NEAREST_NEIGHBOUR': 'const'
    'IMG_WEIGHTED4': 'const'
    'IMG_TRIANGLE': 'const'
    # GD functions
    'gd_info': 'function'
    'getimagesize': 'function'
    'getimagesizefromstring': 'function'
    'image_type_to_extension': 'function'
    'image_type_to_mime_type': 'function'
    'image2wbmp': 'function'
    'imageaffine': 'function'
    'imageaffinematrixconcat': 'function'
    'imageaffinematrixget': 'function'
    'imagealphablending': 'function'
    'imageantialias': 'function'
    'imagearc': 'function'
    'imagechar': 'function'
    'imagecharup': 'function'
    'imagecolorallocate': 'function'
    'imagecolorallocatealpha': 'function'
    'imagecolorat': 'function'
    'imagecolorclosest': 'function'
    'imagecolorclosestalpha': 'function'
    'imagecolorclosesthwb': 'function'
    'imagecolordeallocate': 'function'
    'imagecolorexact': 'function'
    'imagecolorexactalpha': 'function'
    'imagecolormatch': 'function'
    'imagecolorresolve': 'function'
    'imagecolorresolvealpha': 'function'
    'imagecolorset': 'function'
    'imagecolorsforindex': 'function'
    'imagecolorstotal': 'function'
    'imagecolortransparent': 'function'
    'imageconvolution': 'function'
    'imagecopy': 'function'
    'imagecopymerge': 'function'
    'imagecopymergegray': 'function'
    'imagecopyresampled': 'function'
    'imagecopyresized': 'function'
    'imagecreate': 'function'
    'imagecreatefromgd2': 'function'
    'imagecreatefromgd2part': 'function'
    'imagecreatefromgd': 'function'
    'imagecreatefromgif': 'function'
    'imagecreatefromjpeg': 'function'
    'imagecreatefrompng': 'function'
    'imagecreatefromstring': 'function'
    'imagecreatefromwbmp': 'function'
    'imagecreatefromwebp': 'function'
    'imagecreatefromxbm': 'function'
    'imagecreatefromxpm': 'function'
    'imagecreatetruecolor': 'function'
    'imagecrop': 'function'
    'imagecropauto': 'function'
    'imagedashedline': 'function'
    'imagedestroy': 'function'
    'imageellipse': 'function'
    'imagefill': 'function'
    'imagefilledarc': 'function'
    'imagefilledellipse': 'function'
    'imagefilledpolygon': 'function'
    'imagefilledrectangle': 'function'
    'imagefilltoborder': 'function'
    'imagefilter': 'function'
    'imageflip': 'function'
    'imagefontheight': 'function'
    'imagefontwidth': 'function'
    'imageftbbox': 'function'
    'imagefttext': 'function'
    'imagegammacorrect': 'function'
    'imagegd2': 'function'
    'imagegd': 'function'
    'imagegif': 'function'
    'imagegrabscreen': 'function'
    'imagegrabwindow': 'function'
    'imageinterlace': 'function'
    'imageistruecolor': 'function'
    'imagejpeg': 'function'
    'imagelayereffect': 'function'
    'imageline': 'function'
    'imageloadfont': 'function'
    'imagepalettecopy': 'function'
    'imagepalettetotruecolor': 'function'
    'imagepng': 'function'
    'imagepolygon': 'function'
    'imagepsbbox': 'function'
    'imagepsencodefont': 'function'
    'imagepsextendfont': 'function'
    'imagepsfreefont': 'function'
    'imagepsloadfont': 'function'
    'imagepsslantfont': 'function'
    'imagepstext': 'function'
    'imagerectangle': 'function'
    'imagerotate': 'function'
    'imagesavealpha': 'function'
    'imagescale': 'function'
    'imagesetbrush': 'function'
    'imagesetinterpolation': 'function'
    'imagesetpixel': 'function'
    'imagesetstyle': 'function'
    'imagesetthickness': 'function'
    'imagesettile': 'function'
    'imagestring': 'function'
    'imagestringup': 'function'
    'imagesx': 'function'
    'imagesy': 'function'
    'imagetruecolortopalette': 'function'
    'imagettfbbox': 'function'
    'imagettftext': 'function'
    'imagetypes': 'function'
    'imagewbmp': 'function'
    'imagewebp': 'function'
    'imagexbm': 'function'
    'iptcembed': 'function'
    'iptcparse': 'function'
    'jpeg2wbmp': 'function'
    'png2wbmp': 'function'

    # Gmagick
    # Gmagick classes
    'Gmagick': 'class'
    'GmagickDraw': 'class'
    'GmagickPixel': 'class'

    # ImageMagick
    # ImageMagick classes
    'Imagick': 'class'
    'ImagickDraw': 'class'
    'ImagickPixel': 'class'
    'ImagickPixelIterator': 'class'
    'ImagickKernel': 'class'


    ### Compression and Archive Extensions ###

    # Bzip2
    # Bzip2 functions
    'bzclose': 'function'
    'bzcompress': 'function'
    'bzdecompress': 'function'
    'bzerrno': 'function'
    'bzerror': 'function'
    'bzerrstr': 'function'
    'bzflush': 'function'
    'bzopen': 'function'
    'bzread': 'function'
    'bzwrite': 'function'

    # LZF
    # LZF functions
    'lzf_compress': 'function'
    'lzf_decompress': 'function'
    'lzf_optimized_for': 'function'

    # Phar
    # Phar classes
    'Phar': 'class'
    'PharData': 'class'
    'PharFileInfo': 'class'
    'PharException': 'class'

    # Rar
    # Rar classes
    'RarArchive': 'class'
    'RarEntry': 'class'
    'RarException': 'class'
    # Rar constants
    'RAR_HOST_MSDOS': 'const'
    'RAR_HOST_OS2': 'const'
    'RAR_HOST_WIN32': 'const'
    'RAR_HOST_UNIX': 'const'
    'RAR_HOST_BEOS': 'const'
    # Rar functions
    'rar_wrapper_cache_stats': 'function'

    # Zip
    # Zip classes
    'ZipArchive': 'class'
    # Zip functions
    'zip_close': 'function'
    'zip_entry_close': 'function'
    'zip_entry_compressedsize': 'function'
    'zip_entry_compressionmethod': 'function'
    'zip_entry_filesize': 'function'
    'zip_entry_name': 'function'
    'zip_entry_open': 'function'
    'zip_entry_read': 'function'
    'zip_open': 'function'
    'zip_read': 'function'

    # Zlib
    # Zlib constants
    'FORCE_GZIP': 'const'
    'FORCE_DEFLATE': 'const'
    # Zlib functions
    'gzclose': 'function'
    'gzcompress': 'function'
    'gzdecode': 'function'
    'gzdeflate': 'function'
    'gzencode': 'function'
    'gzeof': 'function'
    'gzfile': 'function'
    'gzgetc': 'function'
    'gzgets': 'function'
    'gzgetss': 'function'
    'gzinflate': 'function'
    'gzopen': 'function'
    'gzpassthru': 'function'
    'gzputs': 'function'
    'gzread': 'function'
    'gzrewind': 'function'
    'gzseek': 'function'
    'gztell': 'function'
    'gzuncompress': 'function'
    'gzwrite': 'function'
    'readgzfile': 'function'
    'zlib_decode': 'function'
    'zlib_encode': 'function'
    'zlib_get_coding_type': 'function'


    ### Cryptography Extensions ###

    # Crack
    # Crack functions
    'crack_check': 'function'
    'crack_closedict': 'function'
    'crack_getlastmessage': 'function'
    'crack_opendict': 'function'

    # Hash
    # Hash constants
    'HASH_HMAC': 'const'
    # Hash functions
    'hash_algos': 'function'
    'hash_copy': 'function'
    'hash_file': 'function'
    'hash_final': 'function'
    'hash_hmac_file': 'function'
    'hash_hmac': 'function'
    'hash_init': 'function'
    'hash_pbkdf2': 'function'
    'hash_update_file': 'function'
    'hash_update_stream': 'function'
    'hash_update': 'function'
    'hash': 'function'

    # Mcrypt
    # Mcrypt constants
    'MCRYPT_MODE_ECB': 'const'
    'MCRYPT_MODE_CBC': 'const'
    'MCRYPT_MODE_CFB': 'const'
    'MCRYPT_MODE_OFB': 'const'
    'MCRYPT_MODE_NOFB': 'const'
    'MCRYPT_MODE_STREAM': 'const'
    'MCRYPT_ENCRYPT': 'const'
    'MCRYPT_DECRYPT': 'const'
    'MCRYPT_DEV_RANDOM': 'const'
    'MCRYPT_DEV_URANDOM': 'const'
    'MCRYPT_RAND': 'const' 
    # Mcrypt functions
    'mcrypt_cbc': 'function'
    'mcrypt_cfb': 'function'
    'mcrypt_create_iv': 'function'
    'mcrypt_decrypt': 'function'
    'mcrypt_ecb': 'function'
    'mcrypt_enc_get_algorithms_name': 'function'
    'mcrypt_enc_get_block_size': 'function'
    'mcrypt_enc_get_iv_size': 'function'
    'mcrypt_enc_get_key_size': 'function'
    'mcrypt_enc_get_modes_name': 'function'
    'mcrypt_enc_get_supported_key_sizes': 'function'
    'mcrypt_enc_is_block_algorithm_mode': 'function'
    'mcrypt_enc_is_block_algorithm': 'function'
    'mcrypt_enc_is_block_mode': 'function'
    'mcrypt_enc_self_test': 'function'
    'mcrypt_encrypt': 'function'
    'mcrypt_generic_deinit': 'function'
    'mcrypt_generic_end': 'function'
    'mcrypt_generic_init': 'function'
    'mcrypt_generic': 'function'
    'mcrypt_get_block_size': 'function'
    'mcrypt_get_cipher_name': 'function'
    'mcrypt_get_iv_size': 'function'
    'mcrypt_get_key_size': 'function'
    'mcrypt_list_algorithms': 'function'
    'mcrypt_list_modes': 'function'
    'mcrypt_module_close': 'function'
    'mcrypt_module_get_algo_block_size': 'function'
    'mcrypt_module_get_algo_key_size': 'function'
    'mcrypt_module_get_supported_key_sizes': 'function'
    'mcrypt_module_is_block_algorithm_mode': 'function'
    'mcrypt_module_is_block_algorithm': 'function'
    'mcrypt_module_is_block_mode': 'function'
    'mcrypt_module_open': 'function'
    'mcrypt_module_self_test': 'function'
    'mcrypt_ofb': 'function'
    'mdecrypt_generic': 'function'

    # Mhash
    # Mhash constants
    'MHASH_ADLER32': 'const'
    'MHASH_CRC32': 'const'
    'MHASH_CRC32B': 'const'
    'MHASH_GOST': 'const'
    'MHASH_HAVAL128': 'const'
    'MHASH_HAVAL160': 'const'
    'MHASH_HAVAL192': 'const'
    'MHASH_HAVAL224': 'const'
    'MHASH_HAVAL256': 'const'
    'MHASH_MD2': 'const'
    'MHASH_MD4': 'const'
    'MHASH_MD5': 'const'
    'MHASH_RIPEMD128': 'const'
    'MHASH_RIPEMD256': 'const'
    'MHASH_RIPEMD320': 'const'
    'MHASH_SHA1': 'const'
    'MHASH_SHA192': 'const'
    'MHASH_SHA224': 'const'
    'MHASH_SHA256': 'const'
    'MHASH_SHA384': 'const'
    'MHASH_SHA512': 'const'
    'MHASH_SNEFRU128': 'const'
    'MHASH_SNEFRU256': 'const'
    'MHASH_TIGER': 'const'
    'MHASH_TIGER128': 'const'
    'MHASH_TIGER160': 'const'
    'MHASH_WHIRLPOOL ': 'const'
    # Mhash functions
    'mhash_count': 'function'
    'mhash_get_block_size': 'function'
    'mhash_get_hash_name': 'function'
    'mhash_keygen_s2k': 'function'
    'mhash': 'function'

    # OpenSSL
    # OpenSSL constants
    'X509_PURPOSE_SSL_CLIENT': 'const'
    'X509_PURPOSE_SSL_SERVER': 'const'
    'X509_PURPOSE_NS_SSL_SERVER': 'const'
    'X509_PURPOSE_SMIME_SIGN': 'const'
    'X509_PURPOSE_SMIME_ENCRYPT': 'const'
    'X509_PURPOSE_CRL_SIGN': 'const'
    'X509_PURPOSE_ANY': 'const' 
    'OPENSSL_PKCS1_PADDING': 'const'
    'OPENSSL_SSLV23_PADDING': 'const'
    'OPENSSL_NO_PADDING': 'const'
    'OPENSSL_PKCS1_OAEP_PADDING': 'const'
    'OPENSSL_KEYTYPE_RSA': 'const'
    'OPENSSL_KEYTYPE_DSA': 'const'
    'OPENSSL_KEYTYPE_DH': 'const'
    'OPENSSL_KEYTYPE_EC': 'const'
    'OPENSSL_KEYTYPE_EC': 'const'
    'PKCS7_TEXT': 'const'
    'PKCS7_BINARY': 'const'
    'PKCS7_NOINTERN': 'const'
    'PKCS7_NOVERIFY': 'const'
    'PKCS7_NOCHAIN': 'const'
    'PKCS7_NOCERTS': 'const'
    'PKCS7_NOATTR': 'const'
    'PKCS7_DETACHED': 'const'
    'PKCS7_NOSIGS': 'const'
    'OPENSSL_ALGO_DSS1': 'const'
    'OPENSSL_ALGO_SHA1': 'const'
    'OPENSSL_ALGO_SHA224': 'const'
    'OPENSSL_ALGO_SHA256': 'const'
    'OPENSSL_ALGO_SHA384': 'const'
    'OPENSSL_ALGO_SHA512': 'const'
    'OPENSSL_ALGO_RMD160': 'const'
    'OPENSSL_ALGO_MD5': 'const'
    'OPENSSL_ALGO_MD4': 'const'
    'OPENSSL_ALGO_MD2': 'const' 
    'OPENSSL_CIPHER_RC2_40': 'const'
    'OPENSSL_CIPHER_RC2_128': 'const'
    'OPENSSL_CIPHER_RC2_64': 'const'
    'OPENSSL_CIPHER_DES': 'const'
    'OPENSSL_CIPHER_3DES': 'const' 
    'OPENSSL_CIPHER_AES_128_CBC': 'const'
    'OPENSSL_CIPHER_AES_192_CBC': 'const'
    'OPENSSL_CIPHER_AES_256_CBC': 'const' 
    'OPENSSL_VERSION_TEXT': 'const'
    'OPENSSL_VERSION_NUMBER': 'const'
    'OPENSSL_TLSEXT_SERVER_NAME': 'const'
    # OpenSSL functions
    'openssl_cipher_iv_length': 'function'
    'openssl_csr_export_to_file': 'function'
    'openssl_csr_export': 'function'
    'openssl_csr_get_public_key': 'function'
    'openssl_csr_get_subject': 'function'
    'openssl_csr_new': 'function'
    'openssl_csr_sign': 'function'
    'openssl_decrypt': 'function'
    'openssl_dh_compute_key': 'function'
    'openssl_digest': 'function'
    'openssl_encrypt': 'function'
    'openssl_error_string': 'function'
    'openssl_free_key': 'function'
    'openssl_get_cipher_methods': 'function'
    'openssl_get_md_methods': 'function'
    'openssl_get_privatekey': 'function'
    'openssl_get_publickey': 'function'
    'openssl_open': 'function'
    'openssl_pbkdf2': 'function'
    'openssl_pkcs12_export_to_file': 'function'
    'openssl_pkcs12_export': 'function'
    'openssl_pkcs12_read': 'function'
    'openssl_pkcs7_decrypt': 'function'
    'openssl_pkcs7_encrypt': 'function'
    'openssl_pkcs7_sign': 'function'
    'openssl_pkcs7_verify': 'function'
    'openssl_pkey_export_to_file': 'function'
    'openssl_pkey_export': 'function'
    'openssl_pkey_free': 'function'
    'openssl_pkey_get_details': 'function'
    'openssl_pkey_get_private': 'function'
    'openssl_pkey_get_public': 'function'
    'openssl_pkey_new': 'function'
    'openssl_private_decrypt': 'function'
    'openssl_private_encrypt': 'function'
    'openssl_public_decrypt': 'function'
    'openssl_public_encrypt': 'function'
    'openssl_random_pseudo_bytes': 'function'
    'openssl_seal': 'function'
    'openssl_sign': 'function'
    'openssl_spki_export_challenge': 'function'
    'openssl_spki_export': 'function'
    'openssl_spki_new': 'function'
    'openssl_spki_verify': 'function'
    'openssl_verify': 'function'
    'openssl_x509_check_private_key': 'function'
    'openssl_x509_checkpurpose': 'function'
    'openssl_x509_export_to_file': 'function'
    'openssl_x509_export': 'function'
    'openssl_x509_fingerprint': 'function'
    'openssl_x509_free': 'function'
    'openssl_x509_parse': 'function'
    'openssl_x509_read': 'function'

    # Password Hashing
    # Password Hashing constants
    'PASSWORD_BCRYPT': 'const'
    'PASSWORD_DEFAULT': 'const'
    # Password Hashing functions
    'password_get_info': 'function'
    'password_hash': 'function'
    'password_needs_rehash': 'function'
    'password_verify': 'function'


    ### Affecting PHP's Behaviour ###

    # APC
    # APC classes
    'APCIterator': 'class'
    # APC constants
    'APC_BIN_VERIFY_CRC32': 'const'
    'APC_BIN_VERIFY_MD5': 'const'
    'APC_ITER_ALL': 'const'
    'APC_ITER_ATIME': 'const'
    'APC_ITER_CTIME': 'const'
    'APC_ITER_DEVICE': 'const'
    'APC_ITER_DTIME': 'const'
    'APC_ITER_FILENAME': 'const'
    'APC_ITER_INODE': 'const'
    'APC_ITER_KEY': 'const'
    'APC_ITER_MD5': 'const'
    'APC_ITER_MEM_SIZE': 'const'
    'APC_ITER_MTIME': 'const'
    'APC_ITER_NONE': 'const'
    'APC_ITER_NUM_HITS': 'const'
    'APC_ITER_REFCOUNT': 'const'
    'APC_ITER_TTL': 'const'
    'APC_ITER_TYPE': 'const'
    'APC_ITER_VALUE': 'const'
    'APC_LIST_ACTIVE': 'const'
    'APC_LIST_DELETED': 'const' 
    # APC functions
    'apc_add': 'function'
    'apc_bin_dump': 'function'
    'apc_bin_dumpfile': 'function'
    'apc_bin_load': 'function'
    'apc_bin_loadfile': 'function'
    'apc_cache_info': 'function'
    'apc_cas': 'function'
    'apc_clear_cache': 'function'
    'apc_compile_file': 'function'
    'apc_dec': 'function'
    'apc_define_constants': 'function'
    'apc_delete_file': 'function'
    'apc_delete': 'function'
    'apc_exists': 'function'
    'apc_fetch': 'function'
    'apc_inc': 'function'
    'apc_load_constants': 'function'
    'apc_sma_info': 'function'
    'apc_store': 'function'

    # Error handling
    # Error Handling constants
    'E_ERROR': 'const'
    'E_WARNING': 'const'
    'E_PARSE': 'const'
    'E_NOTICE': 'const'
    'E_CORE_ERROR': 'const'
    'E_CORE_WARNING': 'const'
    'E_COMPILE_ERROR': 'const'
    'E_COMPILE_WARNING': 'const'
    'E_USER_ERROR': 'const'
    'E_USER_WARNING': 'const'
    'E_USER_NOTICE': 'const'
    'E_STRICT': 'const'
    'E_RECOVERABLE_ERROR': 'const'
    'E_DEPRECATED': 'const'
    'E_USER_DEPRECATED': 'const'
    'E_ALL': 'const'
    # Error Handling functions
    'debug_backtrace': 'function'
    'debug_print_backtrace': 'function'
    'error_clear_last': 'function'
    'error_get_last': 'function'
    'error_log': 'function'
    'error_reporting': 'function'
    'restore_error_handler': 'function'
    'restore_exception_handler': 'function'
    'set_error_handler': 'function'
    'set_exception_handler': 'function'
    'trigger_error': 'function'
    'user_error': 'function'

    # PHP Options/Info
    # PHP Options/Info constants
    'CREDITS_GROUP': 'const'
    'CREDITS_GENERAL': 'const'
    'CREDITS_SAPI': 'const'
    'CREDITS_MODULES': 'const'
    'CREDITS_DOCS': 'const'
    'CREDITS_FULLPAGE': 'const'
    'CREDITS_QA': 'const'
    'CREDITS_ALL': 'const'
    'INFO_GENERAL': 'const'
    'INFO_CREDITS': 'const'
    'INFO_CONFIGURATION': 'const'
    'INFO_MODULES': 'const'
    'INFO_ENVIRONMENT': 'const'
    'INFO_VARIABLES': 'const'
    'INFO_LICENSE': 'const'
    'INFO_ALL': 'const'
    'INI_USER': 'const'
    'INI_PERDIR': 'const'
    'INI_SYSTEM': 'const'
    'INI_ALL': 'const'
    'SSERT_ACTIVE': 'const'
    'ASSERT_CALLBACK': 'const'
    'ASSERT_BAIL': 'const'
    'ASSERT_WARNING': 'const'
    'ASSERT_QUIET_EVAL': 'const'
    'PHP_WINDOWS_VERSION_MAJOR': 'const'
    'PHP_WINDOWS_VERSION_MINOR': 'const'
    'PHP_WINDOWS_VERSION_BUILD': 'const'
    'PHP_WINDOWS_VERSION_PLATFORM': 'const'
    'PHP_WINDOWS_VERSION_SP_MAJOR': 'const'
    'PHP_WINDOWS_VERSION_SP_MINOR': 'const'
    'PHP_WINDOWS_VERSION_SUITEMASK': 'const'
    'PHP_WINDOWS_VERSION_PRODUCTTYPE': 'const'
    'PHP_WINDOWS_NT_DOMAIN_CONTROLLER': 'const'
    'PHP_WINDOWS_NT_SERVER': 'const'
    'PHP_WINDOWS_NT_WORKSTATION': 'const'
    # PHP Options/Info functions
    'assert_options': 'function'
    'assert': 'function'
    'cli_get_process_title': 'function'
    'cli_set_process_title': 'function'
    'dl': 'function'
    'extension_loaded': 'function'
    'gc_collect_cycles': 'function'
    'gc_disable': 'function'
    'gc_enable': 'function'
    'gc_enabled': 'function'
    'get_cfg_var': 'function'
    'get_current_user': 'function'
    'get_defined_constants': 'function'
    'get_extension_funcs': 'function'
    'get_include_path': 'function'
    'get_included_files': 'function'
    'get_loaded_extensions': 'function'
    'get_magic_quotes_gpc': 'function'
    'get_magic_quotes_runtime': 'function'
    'get_required_files': 'function'
    'getenv': 'function'
    'getlastmod': 'function'
    'getmygid': 'function'
    'getmyinode': 'function'
    'getmypid': 'function'
    'getmyuid': 'function'
    'getopt': 'function'
    'getrusage': 'function'
    'ini_alter': 'function'
    'ini_get_all': 'function'
    'ini_get': 'function'
    'ini_restore': 'function'
    'ini_set': 'function'
    'magic_quotes_runtime': 'function'
    'main': 'function'
    'memory_get_peak_usage': 'function'
    'memory_get_usage': 'function'
    'php_ini_loaded_file': 'function'
    'php_ini_scanned_files': 'function'
    'php_logo_guid': 'function'
    'php_sapi_name': 'function'
    'php_uname': 'function'
    'phpcredits': 'function'
    'phpinfo': 'function'
    'phpversion': 'function'
    'putenv': 'function'
    'restore_include_path': 'function'
    'set_include_path': 'function'
    'set_magic_quotes_runtime': 'function'
    'set_time_limit': 'function'
    'sys_get_temp_dir': 'function'
    'version_compare': 'function'
    'zend_logo_guid': 'function'
    'zend_thread_id': 'function'
    'zend_version': 'function'


    ### Text Processing ###

    # BBCode
    # BBCode constants
    'BBCODE_TYPE_NOARG': 'const'
    'BBCODE_TYPE_SINGLE': 'const'
    'BBCODE_TYPE_ARG': 'const'
    'BBCODE_TYPE_OPTARG': 'const'
    'BBCODE_TYPE_ROOT': 'const'
    'BBCODE_FLAGS_ARG_PARSING': 'const'
    'BBCODE_FLAGS_CDATA_NOT_ALLOWED': 'const'
    'BBCODE_FLAGS_SMILEYS_ON': 'const'
    'BBCODE_FLAGS_SMILEYS_OFF': 'const'
    'BBCODE_FLAGS_ONE_OPEN_PER_LEVEL': 'const'
    'BBCODE_FLAGS_REMOVE_IF_EMPTY': 'const'
    'BBCODE_FLAGS_DENY_REOPEN_CHILD': 'const'
    'BBCODE_ARG_DOUBLE_QUOTE': 'const'
    'BBCODE_ARG_SINGLE_QUOTE': 'const'
    'BBCODE_ARG_HTML_QUOTE': 'const'
    'BBCODE_ARG_QUOTE_ESCAPING': 'const'
    'BBCODE_AUTO_CORRECT': 'const'
    'BBCODE_CORRECT_REOPEN_TAGS': 'const'
    'BBCODE_DISABLE_TREE_BUILD': 'const'
    'BBCODE_DEFAULT_SMILEYS_ON': 'const'
    'BBCODE_DEFAULT_SMILEYS_OFF': 'const'
    'BBCODE_FORCE_SMILEYS_OFF': 'const'
    'BBCODE_SMILEYS_CASE_INSENSITIVE': 'const'
    'BBCODE_SET_FLAGS_SET': 'const'
    'BBCODE_SET_FLAGS_ADD': 'const'
    'BBCODE_SET_FLAGS_REMOVE': 'const'
    # BBCode functions
    'bbcode_add_element': 'function'
    'bbcode_add_smiley': 'function'
    'bbcode_create': 'function'
    'bbcode_destroy': 'function'
    'bbcode_parse': 'function'
    'bbcode_set_arg_parser': 'function'
    'bbcode_set_flags': 'function'

    # PCRE
    # PCRE constants
    'PREG_PATTERN_ORDER': 'const'
    'PREG_SET_ORDER': 'const'
    'PREG_OFFSET_CAPTURE': 'const'
    'PREG_SPLIT_NO_EMPTY': 'const'
    'PREG_SPLIT_DELIM_CAPTURE': 'const'
    'PREG_SPLIT_OFFSET_CAPTURE': 'const'
    'PREG_NO_ERROR': 'const'
    'PREG_INTERNAL_ERROR': 'const'
    'PREG_BACKTRACK_LIMIT_ERROR': 'const'
    'PREG_RECURSION_LIMIT_ERROR': 'const'
    'PREG_BAD_UTF8_ERROR': 'const'
    'PREG_BAD_UTF8_OFFSET_ERROR': 'const'
    'PCRE_VERSION': 'const'
    # PCRE functions
    'preg_filter': 'function'
    'preg_grep': 'function'
    'preg_last_error': 'function'
    'preg_match_all': 'function'
    'preg_match': 'function'
    'preg_quote': 'function'
    'preg_replace_callback_array': 'function'
    'preg_replace_callback': 'function'
    'preg_replace': 'function'
    'preg_split': 'function'

    # POSIX Regex
    # POSIX Regex functions
    'ereg_replace': 'function'
    'ereg': 'function'
    'eregi_replace': 'function'
    'eregi': 'function'
    'split': 'function'
    'spliti': 'function'
    'sql_regcase': 'function'

    # ssdeep
    # ssdeep functions
    'ssdeep_fuzzy_compare': 'function'
    'ssdeep_fuzzy_hash_filename': 'function'
    'ssdeep_fuzzy_hash': 'function'

    # Strings
    # Strings constants
    'CRYPT_SALT_LENGTH': 'const'
    'CRYPT_STD_DES': 'const'
    'CRYPT_EXT_DES': 'const'
    'CRYPT_MD5': 'const'
    'CRYPT_BLOWFISH': 'const'
    'HTML_SPECIALCHARS': 'const'
    'HTML_ENTITIES': 'const'
    'ENT_COMPAT': 'const'
    'ENT_QUOTES': 'const'
    'ENT_NOQUOTES': 'const'
    'ENT_IGNORE': 'const'
    'ENT_SUBSTITUTE': 'const'
    'ENT_DISALLOWED': 'const'
    'ENT_HTML401': 'const'
    'ENT_XML1': 'const'
    'ENT_XHTML': 'const'
    'ENT_HTML5': 'const'
    'CHAR_MAX': 'const'
    'LC_CTYPE': 'const'
    'LC_NUMERIC': 'const'
    'LC_TIME': 'const'
    'LC_COLLATE': 'const'
    'LC_MONETARY': 'const'
    'LC_ALL': 'const'
    'LC_MESSAGES': 'const'
    'STR_PAD_LEFT': 'const'
    'STR_PAD_RIGHT': 'const'
    'STR_PAD_BOTH': 'const'
    # Strings functions
    'addcslashes': 'function'
    'addslashes': 'function'
    'bin2hex': 'function'
    'chop': 'function'
    'chr': 'function'
    'chunk_split': 'function'
    'convert_cyr_string': 'function'
    'convert_uudecode': 'function'
    'convert_uuencode': 'function'
    'count_chars': 'function'
    'crc32': 'function'
    'crypt': 'function'
    'echo': 'function'
    'explode': 'function'
    'fprintf': 'function'
    'get_html_translation_table': 'function'
    'hebrev': 'function'
    'hebrevc': 'function'
    'hex2bin': 'function'
    'html_entity_decode': 'function'
    'htmlentities': 'function'
    'htmlspecialchars_decode': 'function'
    'htmlspecialchars': 'function'
    'implode': 'function'
    'join': 'function'
    'lcfirst': 'function'
    'levenshtein': 'function'
    'localeconv': 'function'
    'ltrim': 'function'
    'md5_file': 'function'
    'md5': 'function'
    'metaphone': 'function'
    'money_format': 'function'
    'nl_langinfo': 'function'
    'nl2br': 'function'
    'number_format': 'function'
    'ord': 'function'
    'parse_str': 'function'
    'print': 'function'
    'printf': 'function'
    'quoted_printable_decode': 'function'
    'quoted_printable_encode': 'function'
    'quotemeta': 'function'
    'rtrim': 'function'
    'setlocale': 'function'
    'sha1_file': 'function'
    'sha1': 'function'
    'similar_text': 'function'
    'soundex': 'function'
    'sprintf': 'function'
    'sscanf': 'function'
    'str_getcsv': 'function'
    'str_ireplace': 'function'
    'str_pad': 'function'
    'str_repeat': 'function'
    'str_replace': 'function'
    'str_rot13': 'function'
    'str_shuffle': 'function'
    'str_split': 'function'
    'str_word_count': 'function'
    'strcasecmp': 'function'
    'strchr': 'function'
    'strcmp': 'function'
    'strcoll': 'function'
    'strcspn': 'function'
    'strip_tags': 'function'
    'stripcslashes': 'function'
    'stripos': 'function'
    'stripslashes': 'function'
    'stristr': 'function'
    'strlen': 'function'
    'strnatcasecmp': 'function'
    'strnatcmp': 'function'
    'strncasecmp': 'function'
    'strncmp': 'function'
    'strpbrk': 'function'
    'strpos': 'function'
    'strrchr': 'function'
    'strrev': 'function'
    'strripos': 'function'
    'strrpos': 'function'
    'strspn': 'function'
    'strstr': 'function'
    'strtok': 'function'
    'strtolower': 'function'
    'strtoupper': 'function'
    'strtr': 'function'
    'substr_compare': 'function'
    'substr_count': 'function'
    'substr_replace': 'function'
    'substr': 'function'
    'trim': 'function'
    'ucfirst': 'function'
    'ucwords': 'function'
    'vfprintf': 'function'
    'vprintf': 'function'
    'vsprintf': 'function'
    'wordwrap': 'function'


    ### Mail Related Extensions ###

    # Cyrus
    # Cyrus constants
    'CYRUS_CONN_NONSYNCLITERAL': 'const'
    'CYRUS_CONN_INITIALRESPONSE': 'const'
    'CYRUS_CALLBACK_NUMBERED': 'const'
    'CYRUS_CALLBACK_NOLITERAL': 'const'
    # Cyrus functions
    'cyrus_authenticate': 'function'
    'cyrus_bind': 'function'
    'cyrus_close': 'function'
    'cyrus_connect': 'function'
    'cyrus_query': 'function'
    'cyrus_unbind': 'function'

    # IMAP
    # IMAP constants
    'NIL': 'const'
    'OP_DEBUG': 'const'
    'OP_READONLY': 'const'
    'OP_ANONYMOUS': 'const'
    'OP_SHORTCACHE': 'const'
    'OP_SILENT': 'const'
    'OP_PROTOTYPE': 'const'
    'OP_HALFOPEN': 'const'
    'OP_EXPUNGE': 'const'
    'OP_SECURE': 'const'
    'CL_EXPUNGE': 'const'
    'FT_UID': 'const'
    'FT_PEEK': 'const'
    'FT_NOT': 'const'
    'FT_INTERNAL': 'const'
    'FT_PREFETCHTEXT': 'const'
    'ST_UID': 'const'
    'ST_SILENT': 'const'
    'ST_SET': 'const'
    'CP_UID': 'const'
    'CP_MOVE': 'const'
    'SE_UID': 'const'
    'SE_FREE': 'const'
    'SE_NOPREFETCH': 'const'
    'SO_FREE': 'const'
    'SO_NOSERVER': 'const'
    'SA_MESSAGES': 'const'
    'SA_RECENT': 'const'
    'SA_UNSEEN': 'const'
    'SA_UIDNEXT': 'const'
    'SA_UIDVALIDITY': 'const'
    'SA_ALL': 'const'
    'LATT_NOINFERIORS': 'const'
    'LATT_NOSELECT': 'const'
    'LATT_MARKED': 'const'
    'LATT_UNMARKED': 'const'
    'SORTDATE': 'const'
    'SORTARRIVAL': 'const'
    'SORTFROM': 'const'
    'SORTSUBJECT': 'const'
    'SORTTO': 'const'
    'SORTCC': 'const'
    'SORTSIZE': 'const'
    'TYPETEXT': 'const'
    'TYPEMULTIPART': 'const'
    'TYPEMESSAGE': 'const'
    'TYPEAPPLICATION': 'const'
    'TYPEAUDIO': 'const'
    'TYPEIMAGE': 'const'
    'TYPEVIDEO': 'const'
    'TYPEMODEL': 'const'
    'TYPEOTHER': 'const'
    'ENC7BIT': 'const'
    'ENC8BIT': 'const'
    'ENCBINARY': 'const'
    'ENCBASE64': 'const'
    'ENCQUOTEDPRINTABLE': 'const'
    'ENCOTHER': 'const'
    'IMAP_OPENTIMEOUT': 'const'
    'IMAP_READTIMEOUT': 'const'
    'IMAP_WRITETIMEOUT': 'const'
    'IMAP_CLOSETIMEOUT': 'const'
    'LATT_REFERRAL': 'const'
    'LATT_HASCHILDREN': 'const'
    'LATT_HASNOCHILDREN': 'const'
    'IMAP_GC_ELT': 'const'
    'IMAP_GC_ENV': 'const'
    'IMAP_GC_TEXTS': 'const'
    # IMAP functions
    'imap_8bit': 'function'
    'imap_alerts': 'function'
    'imap_append': 'function'
    'imap_base64': 'function'
    'imap_binary': 'function'
    'imap_body': 'function'
    'imap_bodystruct': 'function'
    'imap_check': 'function'
    'imap_clearflag_full': 'function'
    'imap_close': 'function'
    'imap_create': 'function'
    'imap_createmailbox': 'function'
    'imap_delete': 'function'
    'imap_deletemailbox': 'function'
    'imap_errors': 'function'
    'imap_expunge': 'function'
    'imap_fetch_overview': 'function'
    'imap_fetchbody': 'function'
    'imap_fetchheader': 'function'
    'imap_fetchmime': 'function'
    'imap_fetchstructure': 'function'
    'imap_fetchtext': 'function'
    'imap_gc': 'function'
    'imap_get_quota': 'function'
    'imap_get_quotaroot': 'function'
    'imap_getacl': 'function'
    'imap_getmailboxes': 'function'
    'imap_getsubscribed': 'function'
    'imap_header': 'function'
    'imap_headerinfo': 'function'
    'imap_headers': 'function'
    'imap_last_error': 'function'
    'imap_list': 'function'
    'imap_listmailbox': 'function'
    'imap_listscan': 'function'
    'imap_listsubscribed': 'function'
    'imap_lsub': 'function'
    'imap_mail_compose': 'function'
    'imap_mail_copy': 'function'
    'imap_mail_move': 'function'
    'imap_mail': 'function'
    'imap_mailboxmsginfo': 'function'
    'imap_mime_header_decode': 'function'
    'imap_msgno': 'function'
    'imap_num_msg': 'function'
    'imap_num_recent': 'function'
    'imap_open': 'function'
    'imap_ping': 'function'
    'imap_qprint': 'function'
    'imap_rename': 'function'
    'imap_renamemailbox': 'function'
    'imap_reopen': 'function'
    'imap_rfc822_parse_adrlist': 'function'
    'imap_rfc822_parse_headers': 'function'
    'imap_rfc822_write_address': 'function'
    'imap_savebody': 'function'
    'imap_scan': 'function'
    'imap_scanmailbox': 'function'
    'imap_search': 'function'
    'imap_set_quota': 'function'
    'imap_setacl': 'function'
    'imap_setflag_full': 'function'
    'imap_sort': 'function'
    'imap_status': 'function'
    'imap_subscribe': 'function'
    'imap_thread': 'function'
    'imap_timeout': 'function'
    'imap_uid': 'function'
    'imap_undelete': 'function'
    'imap_unsubscribe': 'function'
    'imap_utf7_decode': 'function'
    'imap_utf7_encode': 'function'
    'imap_utf8': 'function'

    # Mail
    # Mail functions
    'ezmlm_hash': 'function'
    'mail': 'function'

    # Mailparse
    # Mailparse constants
    'MAILPARSE_EXTRACT_OUTPUT': 'const'
    'MAILPARSE_EXTRACT_STREAM': 'const'
    'MAILPARSE_EXTRACT_RETURN': 'const'
    # Mailparse functions
    'mailparse_determine_best_xfer_encoding': 'function'
    'mailparse_msg_create': 'function'
    'mailparse_msg_extract_part_file': 'function'
    'mailparse_msg_extract_part': 'function'
    'mailparse_msg_extract_whole_part_file': 'function'
    'mailparse_msg_free': 'function'
    'mailparse_msg_get_part_data': 'function'
    'mailparse_msg_get_part': 'function'
    'mailparse_msg_get_structure': 'function'
    'mailparse_msg_parse_file': 'function'
    'mailparse_msg_parse': 'function'
    'mailparse_rfc822_parse_addresses': 'function'
    'mailparse_stream_encode': 'function'
    'mailparse_uudecode_all': 'function'

    # vpopmail
    # vpopmail functions
    'vpopmail_add_alias_domain_ex': 'function'
    'vpopmail_add_alias_domain': 'function'
    'vpopmail_add_domain_ex': 'function'
    'vpopmail_add_domain': 'function'
    'vpopmail_add_user': 'function'
    'vpopmail_alias_add': 'function'
    'vpopmail_alias_del_domain': 'function'
    'vpopmail_alias_del': 'function'
    'vpopmail_alias_get_all': 'function'
    'vpopmail_alias_get': 'function'
    'vpopmail_auth_user': 'function'
    'vpopmail_del_domain_ex': 'function'
    'vpopmail_del_domain': 'function'
    'vpopmail_del_user': 'function'
    'vpopmail_error': 'function'
    'vpopmail_passwd': 'function'
    'vpopmail_set_user_quota': 'function'


    ### Mathematical Extensions ###

    # Math
    # Math constants
    'M_PI': 'const'
    'M_E': 'const'
    'M_LOG2E': 'const'
    'M_LOG10E': 'const'
    'M_LN2': 'const'
    'M_LN10': 'const'
    'M_PI_2': 'const'
    'M_PI_4': 'const'
    'M_1_PI': 'const'
    'M_2_PI': 'const'
    'M_SQRTPI': 'const'
    'M_2_SQRTPI': 'const'
    'M_SQRT2': 'const'
    'M_SQRT3': 'const'
    'M_SQRT1_2': 'const'
    'M_LNPI': 'const'
    'M_EULER': 'const'
    'PHP_ROUND_HALF_UP': 'const'
    'PHP_ROUND_HALF_DOWN': 'const'
    'PHP_ROUND_HALF_EVEN': 'const'
    'PHP_ROUND_HALF_ODD': 'const'
    'NAN': 'const'
    'INF': 'const'
    # Math functions
    'abs': 'function'
    'acos': 'function'
    'acosh': 'function'
    'asin': 'function'
    'asinh': 'function'
    'atan2': 'function'
    'atan': 'function'
    'atanh': 'function'
    'base_convert': 'function'
    'bindec': 'function'
    'ceil': 'function'
    'cos': 'function'
    'cosh': 'function'
    'decbin': 'function'
    'dechex': 'function'
    'decoct': 'function'
    'deg2rad': 'function'
    'exp': 'function'
    'expm1': 'function'
    'floor': 'function'
    'fmod': 'function'
    'getrandmax': 'function'
    'hexdec': 'function'
    'hypot': 'function'
    'intdiv': 'function'
    'is_finite': 'function'
    'is_infinite': 'function'
    'is_nan': 'function'
    'lcg_value': 'function'
    'log10': 'function'
    'log1p': 'function'
    'log': 'function'
    'max': 'function'
    'min': 'function'
    'mt_getrandmax': 'function'
    'mt_rand': 'function'
    'mt_srand': 'function'
    'octdec': 'function'
    'pi': 'function'
    'pow': 'function'
    'rad2deg': 'function'
    'rand': 'function'
    'round': 'function'
    'sin': 'function'
    'sinh': 'function'
    'sqrt': 'function'
    'srand': 'function'
    'tan': 'function'
    'tanh': 'function'


    ### Other Basic Extensions ###

    # GeoIP
    # GeoIP constants
    'GEOIP_COUNTRY_EDITION': 'const'
    'GEOIP_REGION_EDITION_REV0': 'const'
    'GEOIP_CITY_EDITION_REV0': 'const'
    'GEOIP_ORG_EDITION': 'const'
    'GEOIP_ISP_EDITION': 'const'
    'GEOIP_CITY_EDITION_REV1': 'const'
    'GEOIP_REGION_EDITION_REV1': 'const'
    'GEOIP_PROXY_EDITION': 'const'
    'GEOIP_ASNUM_EDITION': 'const'
    'GEOIP_NETSPEED_EDITION': 'const'
    'GEOIP_DOMAIN_EDITION': 'const'
    'GEOIP_UNKNOWN_SPEED': 'const'
    'GEOIP_DIALUP_SPEED': 'const'
    'GEOIP_CABLEDSL_SPEED': 'const'
    'GEOIP_CORPORATE_SPEED': 'const' 
    # GeoIP functions
    'geoip_asnum_by_name': 'function'
    'geoip_continent_code_by_name': 'function'
    'geoip_country_code_by_name': 'function'
    'geoip_country_code3_by_name': 'function'
    'geoip_country_name_by_name': 'function'
    'geoip_database_info': 'function'
    'geoip_db_avail': 'function'
    'geoip_db_filename': 'function'
    'geoip_db_get_all_info': 'function'
    'geoip_domain_by_name': 'function'
    'geoip_id_by_name': 'function'
    'geoip_isp_by_name': 'function'
    'geoip_netspeedcell_by_name': 'function'
    'geoip_org_by_name': 'function'
    'geoip_record_by_name': 'function'
    'geoip_region_by_name': 'function'
    'geoip_region_name_by_code': 'function'
    'geoip_setup_custom_directory': 'function'
    'geoip_time_zone_by_country_and_region': 'function'

    # JSON
    # JSON classes
    'JsonSerializable': 'class'
    # JSON constants
    'JSON_ERROR_NONE': 'const'
    'JSON_ERROR_DEPTH': 'const'
    'JSON_ERROR_STATE_MISMATCH': 'const'
    'JSON_ERROR_CTRL_CHAR': 'const'
    'JSON_ERROR_SYNTAX': 'const'
    'JSON_ERROR_UTF8': 'const'
    'JSON_ERROR_RECURSION': 'const'
    'JSON_ERROR_INF_OR_NAN': 'const'
    'JSON_ERROR_UNSUPPORTED_TYPE': 'const'
    'JSON_HEX_TAG': 'const'
    'JSON_HEX_AMP': 'const'
    'JSON_HEX_APOS': 'const'
    'JSON_HEX_QUOT': 'const'
    'JSON_FORCE_OBJECT': 'const'
    'JSON_NUMERIC_CHECK': 'const'
    'JSON_BIGINT_AS_STRING': 'const'
    'JSON_PRETTY_PRINT': 'const'
    'JSON_UNESCAPED_SLASHES': 'const'
    'JSON_UNESCAPED_UNICODE': 'const'
    'JSON_PARTIAL_OUTPUT_ON_ERROR': 'const'
    'JSON_PRESERVE_ZERO_FRACTION': 'const'
    # JSON functions
    'json_decode': 'function'
    'json_encode': 'function'
    'json_last_error_msg': 'function'
    'json_last_error': 'function'

    # URLs
    # URLs constants
    'PHP_URL_SCHEME': 'const'
    'PHP_URL_HOST': 'const'
    'PHP_URL_PORT': 'const'
    'PHP_URL_USER': 'const'
    'PHP_URL_PASS': 'const'
    'PHP_URL_PATH': 'const'
    'PHP_URL_QUERY': 'const'
    'PHP_URL_FRAGMENT': 'const'
    'PHP_QUERY_RFC1738': 'const'
    'PHP_QUERY_RFC3986': 'const'
    # URLs functions
    'base64_decode': 'function'
    'base64_encode': 'function'
    'get_headers': 'function'
    'get_meta_tags': 'function'
    'http_build_query': 'function'
    'parse_url': 'function'
    'rawurldecode': 'function'
    'rawurlencode': 'function'
    'urldecode': 'function'
    'urlencode': 'function'

    # YAML
    # YAML constants
    'YAML_ANY_SCALAR_STYLE': 'const'
    'YAML_PLAIN_SCALAR_STYLE': 'const'
    'YAML_SINGLE_QUOTED_SCALAR_STYLE': 'const'
    'YAML_DOUBLE_QUOTED_SCALAR_STYLE': 'const'
    'YAML_LITERAL_SCALAR_STYLE': 'const'
    'YAML_FOLDED_SCALAR_STYLE': 'const'
    'YAML_NULL_TAG': 'const'
    'YAML_BOOL_TAG': 'const'
    'YAML_STR_TAG': 'const'
    'YAML_INT_TAG': 'const'
    'YAML_FLOAT_TAG': 'const'
    'YAML_TIMESTAMP_TAG': 'const'
    'YAML_SEQ_TAG': 'const'
    'YAML_MAP_TAG': 'const'
    'YAML_PHP_TAG': 'const'
    'YAML_ANY_ENCODING': 'const'
    'YAML_UTF8_ENCODING': 'const'
    'YAML_UTF16LE_ENCODING': 'const'
    'YAML_UTF16BE_ENCODING': 'const'
    'YAML_ANY_BREAK': 'const'
    'YAML_CR_BREAK': 'const'
    'YAML_LN_BREAK': 'const'
    'YAML_CRLN_BREAK': 'const'
    # YAML functions
    'yaml_emit_file': 'function'
    'yaml_emit': 'function'
    'yaml_parse_file': 'function'
    'yaml_parse_url': 'function'
    'yaml_parse': 'function'


    ### Other Services ###

    # cURL
    # cURL classes
    'CURLFile': 'class'
    # cURL constants
    'CURLOPT_AUTOREFERER': 'const'
    'CURLOPT_COOKIESESSION': 'const'
    'CURLOPT_DNS_USE_GLOBAL_CACHE': 'const'
    'CURLOPT_DNS_CACHE_TIMEOUT': 'const'
    'CURLOPT_FTP_SSL': 'const'
    'CURLFTPSSL_TRY': 'const'
    'CURLFTPSSL_ALL': 'const'
    'CURLFTPSSL_CONTROL': 'const'
    'CURLFTPSSL_NONE': 'const'
    'CURLOPT_PRIVATE': 'const'
    'CURLOPT_FTPSSLAUTH': 'const'
    'CURLOPT_PORT': 'const'
    'CURLOPT_FILE': 'const'
    'CURLOPT_INFILE': 'const'
    'CURLOPT_INFILESIZE': 'const'
    'CURLOPT_URL': 'const'
    'CURLOPT_PROXY': 'const'
    'CURLOPT_VERBOSE': 'const'
    'CURLOPT_HEADER': 'const'
    'CURLOPT_HTTPHEADER': 'const'
    'CURLOPT_NOPROGRESS': 'const'
    'CURLOPT_NOBODY': 'const'
    'CURLOPT_FAILONERROR': 'const'
    'CURLOPT_UPLOAD': 'const'
    'CURLOPT_POST': 'const'
    'CURLOPT_FTPLISTONLY': 'const'
    'CURLOPT_FTPAPPEND': 'const'
    'CURLOPT_FTP_CREATE_MISSING_DIRS': 'const'
    'CURLOPT_NETRC': 'const'
    'CURLOPT_FOLLOWLOCATION': 'const'
    'CURLOPT_FTPASCII': 'const'
    'CURLOPT_PUT': 'const'
    'CURLOPT_MUTE': 'const'
    'CURLOPT_USERPWD': 'const'
    'CURLOPT_PROXYUSERPWD': 'const'
    'CURLOPT_RANGE': 'const'
    'CURLOPT_TIMEOUT': 'const'
    'CURLOPT_TIMEOUT_MS': 'const'
    'CURLOPT_TCP_NODELAY': 'const'
    'CURLOPT_POSTFIELDS': 'const'
    'CURLOPT_PROGRESSFUNCTION': 'const'
    'CURLOPT_REFERER': 'const'
    'CURLOPT_USERAGENT': 'const'
    'CURLOPT_FTPPORT': 'const'
    'CURLOPT_FTP_USE_EPSV': 'const'
    'CURLOPT_LOW_SPEED_LIMIT': 'const'
    'CURLOPT_LOW_SPEED_TIME': 'const'
    'CURLOPT_RESUME_FROM': 'const'
    'CURLOPT_COOKIE': 'const'
    'CURLOPT_SSLCERT': 'const'
    'CURLOPT_SSLCERTPASSWD': 'const'
    'CURLOPT_WRITEHEADER': 'const'
    'CURLOPT_SSL_VERIFYHOST': 'const'
    'CURLOPT_COOKIEFILE': 'const'
    'CURLOPT_SSLVERSION': 'const'
    'CURL_SSLVERSION_DEFAULT': 'const'
    'CURL_SSLVERSION_TLSv1': 'const'
    'CURL_SSLVERSION_SSLv2': 'const'
    'CURL_SSLVERSION_SSLv3': 'const'
    'CURL_SSLVERSION_TLSv1_0': 'const'
    'CURL_SSLVERSION_TLSv1_1': 'const'
    'CURL_SSLVERSION_TLSv1_2': 'const'
    'CURLOPT_TIMECONDITION': 'const'
    'CURLOPT_TIMEVALUE': 'const'
    'CURLOPT_CUSTOMREQUEST': 'const'
    'CURLOPT_STDERR': 'const'
    'CURLOPT_TRANSFERTEXT': 'const'
    'CURLOPT_RETURNTRANSFER': 'const'
    'CURLOPT_QUOTE': 'const'
    'CURLOPT_POSTQUOTE': 'const'
    'CURLOPT_INTERFACE': 'const'
    'CURLOPT_KRB4LEVEL': 'const'
    'CURLOPT_HTTPPROXYTUNNEL': 'const'
    'CURLOPT_FILETIME': 'const'
    'CURLOPT_WRITEFUNCTION': 'const'
    'CURLOPT_READFUNCTION': 'const'
    'CURLOPT_PASSWDFUNCTION': 'const'
    'CURLOPT_HEADERFUNCTION': 'const'
    'CURLOPT_MAXREDIRS': 'const'
    'CURLOPT_MAXCONNECTS': 'const'
    'CURLOPT_CLOSEPOLICY': 'const'
    'CURLOPT_FRESH_CONNECT': 'const'
    'CURLOPT_FORBID_REUSE': 'const'
    'CURLOPT_RANDOM_FILE': 'const'
    'CURLOPT_EGDSOCKET': 'const'
    'CURLOPT_CONNECTTIMEOUT': 'const'
    'CURLOPT_CONNECTTIMEOUT_MS': 'const'
    'CURLOPT_SSL_VERIFYPEER': 'const'
    'CURLOPT_CAINFO': 'const'
    'CURLOPT_CAPATH': 'const'
    'CURLOPT_COOKIEJAR': 'const'
    'CURLOPT_SSL_CIPHER_LIST': 'const'
    'CURLOPT_BINARYTRANSFER': 'const'
    'CURLOPT_NOSIGNAL': 'const'
    'CURLOPT_PROXYTYPE': 'const'
    'CURLOPT_BUFFERSIZE': 'const'
    'CURLOPT_HTTPGET': 'const'
    'CURLOPT_HTTP_VERSION': 'const'
    'CURLOPT_SSLKEY': 'const'
    'CURLOPT_SSLKEYTYPE': 'const'
    'CURLOPT_SSLKEYPASSWD': 'const'
    'CURLOPT_SSLENGINE': 'const'
    'CURLOPT_SSLENGINE_DEFAULT': 'const'
    'CURLOPT_SSLCERTTYPE': 'const'
    'CURLOPT_CRLF': 'const'
    'CURLOPT_ENCODING': 'const'
    'CURLOPT_PROXYPORT': 'const'
    'CURLOPT_UNRESTRICTED_AUTH': 'const'
    'CURLOPT_FTP_USE_EPRT': 'const'
    'CURLOPT_HTTP200ALIASES': 'const'
    'CURLOPT_HTTPAUTH': 'const'
    'CURLAUTH_BASIC': 'const'
    'CURLAUTH_DIGEST': 'const'
    'CURLAUTH_GSSNEGOTIATE': 'const'
    'CURLAUTH_NTLM': 'const'
    'CURLAUTH_ANY': 'const'
    'CURLAUTH_ANYSAFE': 'const'
    'CURLOPT_PROXYAUTH': 'const'
    'CURLOPT_MAX_RECV_SPEED_LARGE': 'const'
    'CURLOPT_MAX_SEND_SPEED_LARGE': 'const'
    'CURLCLOSEPOLICY_LEAST_RECENTLY_USED': 'const'
    'CURLCLOSEPOLICY_LEAST_TRAFFIC': 'const'
    'CURLCLOSEPOLICY_SLOWEST': 'const'
    'CURLCLOSEPOLICY_CALLBACK': 'const'
    'CURLCLOSEPOLICY_OLDEST': 'const'
    'CURLINFO_PRIVATE': 'const'
    'CURLINFO_EFFECTIVE_URL': 'const'
    'CURLINFO_HTTP_CODE': 'const'
    'CURLINFO_HEADER_OUT': 'const'
    'CURLINFO_HEADER_SIZE': 'const'
    'CURLINFO_REQUEST_SIZE': 'const'
    'CURLINFO_TOTAL_TIME': 'const'
    'CURLINFO_NAMELOOKUP_TIME': 'const'
    'CURLINFO_CONNECT_TIME': 'const'
    'CURLINFO_PRETRANSFER_TIME': 'const'
    'CURLINFO_SIZE_UPLOAD': 'const'
    'CURLINFO_SIZE_DOWNLOAD': 'const'
    'CURLINFO_SPEED_DOWNLOAD': 'const'
    'CURLINFO_SPEED_UPLOAD': 'const'
    'CURLINFO_FILETIME': 'const'
    'CURLINFO_SSL_VERIFYRESULT': 'const'
    'CURLINFO_CONTENT_LENGTH_DOWNLOAD': 'const'
    'CURLINFO_CONTENT_LENGTH_UPLOAD': 'const'
    'CURLINFO_STARTTRANSFER_TIME': 'const'
    'CURLINFO_CONTENT_TYPE': 'const'
    'CURLINFO_REDIRECT_TIME': 'const'
    'CURLINFO_REDIRECT_COUNT': 'const'
    'CURLINFO_REDIRECT_URL': 'const'
    'CURLINFO_PRIMARY_IP': 'const'
    'CURLINFO_PRIMARY_PORT': 'const'
    'CURLINFO_LOCAL_IP': 'const'
    'CURLINFO_LOCAL_PORT': 'const'
    'CURL_TIMECOND_IFMODSINCE': 'const'
    'CURL_TIMECOND_IFUNMODSINCE': 'const'
    'CURL_TIMECOND_LASTMOD': 'const'
    'CURL_VERSION_IPV6': 'const'
    'CURL_VERSION_KERBEROS4': 'const'
    'CURL_VERSION_SSL': 'const'
    'CURL_VERSION_LIBZ': 'const'
    'CURLVERSION_NOW': 'const'
    'CURLE_OK': 'const'
    'CURLE_UNSUPPORTED_PROTOCOL': 'const'
    'CURLE_FAILED_INIT': 'const'
    'CURLE_URL_MALFORMAT': 'const'
    'CURLE_URL_MALFORMAT_USER': 'const'
    'CURLE_COULDNT_RESOLVE_PROXY': 'const'
    'CURLE_COULDNT_RESOLVE_HOST': 'const'
    'CURLE_COULDNT_CONNECT': 'const'
    'CURLE_FTP_WEIRD_SERVER_REPLY': 'const'
    'CURLE_FTP_ACCESS_DENIED': 'const'
    'CURLE_FTP_USER_PASSWORD_INCORRECT': 'const'
    'CURLE_FTP_WEIRD_PASS_REPLY': 'const'
    'CURLE_FTP_WEIRD_USER_REPLY': 'const'
    'CURLE_FTP_WEIRD_PASV_REPLY': 'const'
    'CURLE_FTP_WEIRD_227_FORMAT': 'const'
    'CURLE_FTP_CANT_GET_HOST': 'const'
    'CURLE_FTP_CANT_RECONNECT': 'const'
    'CURLE_FTP_COULDNT_SET_BINARY': 'const'
    'CURLE_PARTIAL_FILE': 'const'
    'CURLE_FTP_COULDNT_RETR_FILE': 'const'
    'CURLE_FTP_WRITE_ERROR': 'const'
    'CURLE_FTP_QUOTE_ERROR': 'const'
    'CURLE_HTTP_NOT_FOUND': 'const'
    'CURLE_WRITE_ERROR': 'const'
    'CURLE_MALFORMAT_USER': 'const'
    'CURLE_FTP_COULDNT_STOR_FILE': 'const'
    'CURLE_READ_ERROR': 'const'
    'CURLE_OUT_OF_MEMORY': 'const'
    'CURLE_OPERATION_TIMEOUTED': 'const'
    'CURLE_FTP_COULDNT_SET_ASCII': 'const'
    'CURLE_FTP_PORT_FAILED': 'const'
    'CURLE_FTP_COULDNT_USE_REST': 'const'
    'CURLE_FTP_COULDNT_GET_SIZE': 'const'
    'CURLE_HTTP_RANGE_ERROR': 'const'
    'CURLE_HTTP_POST_ERROR': 'const'
    'CURLE_SSL_CONNECT_ERROR': 'const'
    'CURLE_FTP_BAD_DOWNLOAD_RESUME': 'const'
    'CURLE_FILE_COULDNT_READ_FILE': 'const'
    'CURLE_LDAP_CANNOT_BIND': 'const'
    'CURLE_LDAP_SEARCH_FAILED': 'const'
    'CURLE_LIBRARY_NOT_FOUND': 'const'
    'CURLE_FUNCTION_NOT_FOUND': 'const'
    'CURLE_ABORTED_BY_CALLBACK': 'const'
    'CURLE_BAD_FUNCTION_ARGUMENT': 'const'
    'CURLE_BAD_CALLING_ORDER': 'const'
    'CURLE_HTTP_PORT_FAILED': 'const'
    'CURLE_BAD_PASSWORD_ENTERED': 'const'
    'CURLE_TOO_MANY_REDIRECTS': 'const'
    'CURLE_UNKNOWN_TELNET_OPTION': 'const'
    'CURLE_TELNET_OPTION_SYNTAX': 'const'
    'CURLE_OBSOLETE': 'const'
    'CURLE_SSL_PEER_CERTIFICATE': 'const'
    'CURLE_GOT_NOTHING': 'const'
    'CURLE_SSL_ENGINE_NOTFOUND': 'const'
    'CURLE_SSL_ENGINE_SETFAILED': 'const'
    'CURLE_SEND_ERROR': 'const'
    'CURLE_RECV_ERROR': 'const'
    'CURLE_SHARE_IN_USE': 'const'
    'CURLE_SSL_CERTPROBLEM': 'const'
    'CURLE_SSL_CIPHER': 'const'
    'CURLE_SSL_CACERT': 'const'
    'CURLE_BAD_CONTENT_ENCODING': 'const'
    'CURLE_LDAP_INVALID_URL': 'const'
    'CURLE_FILESIZE_EXCEEDED': 'const'
    'CURLE_FTP_SSL_FAILED': 'const'
    'CURLE_SSH': 'const'
    'CURLFTPAUTH_DEFAULT': 'const'
    'CURLFTPAUTH_SSL': 'const'
    'CURLFTPAUTH_TLS': 'const'
    'CURLPROXY_HTTP': 'const'
    'CURLPROXY_SOCKS4': 'const'
    'CURLPROXY_SOCKS5': 'const'
    'CURL_NETRC_OPTIONAL': 'const'
    'CURL_NETRC_IGNORED': 'const'
    'CURL_NETRC_REQUIRED': 'const'
    'CURL_HTTP_VERSION_NONE': 'const'
    'CURL_HTTP_VERSION_1_0': 'const'
    'CURL_HTTP_VERSION_1_1': 'const'
    'CURLM_CALL_MULTI_PERFORM': 'const'
    'CURLM_OK': 'const'
    'CURLM_BAD_HANDLE': 'const'
    'CURLM_BAD_EASY_HANDLE': 'const'
    'CURLM_OUT_OF_MEMORY': 'const'
    'CURLM_INTERNAL_ERROR': 'const'
    'CURLMSG_DONE': 'const'
    'CURLOPT_KEYPASSWD': 'const'
    'CURLOPT_SSH_AUTH_TYPES': 'const'
    'CURLOPT_SSH_HOST_PUBLIC_KEY_MD5': 'const'
    'CURLOPT_SSH_PRIVATE_KEYFILE': 'const'
    'CURLOPT_SSH_PUBLIC_KEYFILE': 'const'
    'CURLMOPT_PIPELINING': 'const'
    'CURLMOPT_MAXCONNECTS': 'const'
    'CURLSSH_AUTH_ANY': 'const'
    'CURLSSH_AUTH_DEFAULT': 'const'
    'CURLSSH_AUTH_HOST': 'const'
    'CURLSSH_AUTH_KEYBOARD': 'const'
    'CURLSSH_AUTH_NONE': 'const'
    'CURLSSH_AUTH_PASSWORD': 'const'
    'CURLSSH_AUTH_PUBLICKEY': 'const'
    'CURL_WRAPPERS_ENABLED': 'const'
    'CURLPAUSE_ALL': 'const'
    'CURLPAUSE_CONT': 'const'
    'CURLPAUSE_RECV': 'const'
    'CURLPAUSE_RECV_CONT': 'const'
    'CURLPAUSE_SEND': 'const'
    'CURLPAUSE_SEND_CONT': 'const'
    'CURLPIPE_NOTHING': 'const'
    'CURLPIPE_HTTP1': 'const'
    'CURLPIPE_MULTIPLEX': 'const'
    'CURLPROXY_SOCKS4A': 'const'
    'CURLPROXY_SOCKS5_HOSTNAME': 'const'
    # cURL functions
    'curl_close': 'function'
    'curl_copy_handle': 'function'
    'curl_errno': 'function'
    'curl_error': 'function'
    'curl_escape': 'function'
    'curl_exec': 'function'
    'curl_file_create': 'function'
    'curl_getinfo': 'function'
    'curl_init': 'function'
    'curl_multi_add_handle': 'function'
    'curl_multi_close': 'function'
    'curl_multi_exec': 'function'
    'curl_multi_getcontent': 'function'
    'curl_multi_info_read': 'function'
    'curl_multi_init': 'function'
    'curl_multi_remove_handle': 'function'
    'curl_multi_select': 'function'
    'curl_multi_setopt': 'function'
    'curl_multi_strerror': 'function'
    'curl_pause': 'function'
    'curl_reset': 'function'
    'curl_setopt_array': 'function'
    'curl_setopt': 'function'
    'curl_share_close': 'function'
    'curl_share_init': 'function'
    'curl_share_setopt': 'function'
    'curl_strerror': 'function'
    'curl_unescape': 'function'
    'curl_version': 'function'

    # FTP
    # FTP constants
    'FTP_ASCII': 'const'
    'FTP_TEXT': 'const'
    'FTP_BINARY': 'const'
    'FTP_IMAGE': 'const'
    'FTP_TIMEOUT_SEC': 'const'
    'FTP_AUTOSEEK': 'const'
    'FTP_AUTORESUME': 'const'
    'FTP_FAILED': 'const'
    'FTP_FINISHED': 'const'
    'FTP_MOREDATA': 'const'
    # FTP functions
    'ftp_alloc': 'function'
    'ftp_cdup': 'function'
    'ftp_chdir': 'function'
    'ftp_chmod': 'function'
    'ftp_close': 'function'
    'ftp_connect': 'function'
    'ftp_delete': 'function'
    'ftp_exec': 'function'
    'ftp_fget': 'function'
    'ftp_fput': 'function'
    'ftp_get_option': 'function'
    'ftp_get': 'function'
    'ftp_login': 'function'
    'ftp_mdtm': 'function'
    'ftp_mkdir': 'function'
    'ftp_nb_continue': 'function'
    'ftp_nb_fget': 'function'
    'ftp_nb_fput': 'function'
    'ftp_nb_get': 'function'
    'ftp_nb_put': 'function'
    'ftp_nlist': 'function'
    'ftp_pasv': 'function'
    'ftp_put': 'function'
    'ftp_pwd': 'function'
    'ftp_quit': 'function'
    'ftp_raw': 'function'
    'ftp_rawlist': 'function'
    'ftp_rename': 'function'
    'ftp_rmdir': 'function'
    'ftp_set_option': 'function'
    'ftp_site': 'function'
    'ftp_size': 'function'
    'ftp_ssl_connect': 'function'
    'ftp_systype': 'function'

    # HTTP
    # HTTP class
    'HttpDeflateStream': 'class'
    'HttpInflateStream': 'class'
    'HttpMessage': 'class'
    'HttpQueryString': 'class'
    'HttpRequest': 'class'
    'HttpRequestPool': 'class'
    'HttpResponse': 'class'
    # HTTP constants
    'HTTP_SUPPORT': 'const'
    'HTTP_SUPPORT_REQUESTS': 'const'
    'HTTP_SUPPORT_MAGICMIME': 'const'
    'HTTP_SUPPORT_ENCODINGS': 'const'
    'HTTP_SUPPORT_SSLREQUESTS': 'const'
    'HTTP_PARAMS_ALLOW_COMMA': 'const'
    'HTTP_PARAMS_ALLOW_FAILURE': 'const'
    'HTTP_PARAMS_RAISE_ERROR': 'const'
    'HTTP_PARAMS_DEFAULT': 'const'
    'HTTP_COOKIE_PARSE_RAW': 'const'
    'HTTP_COOKIE_SECURE': 'const'
    'HTTP_COOKIE_HTTPONLY': 'const'
    'HTTP_DEFLATE_LEVEL_DEF': 'const'
    'HTTP_DEFLATE_LEVEL_MIN': 'const'
    'HTTP_DEFLATE_LEVEL_MAX': 'const'
    'HTTP_DEFLATE_TYPE_ZLIB': 'const'
    'HTTP_DEFLATE_TYPE_GZIP': 'const'
    'HTTP_DEFLATE_TYPE_RAW': 'const'
    'HTTP_DEFLATE_STRATEGY_DEF': 'const'
    'HTTP_DEFLATE_STRATEGY_FILT': 'const'
    'HTTP_DEFLATE_STRATEGY_HUFF': 'const'
    'HTTP_DEFLATE_STRATEGY_RLE': 'const'
    'HTTP_DEFLATE_STRATEGY_FIXED': 'const'
    'HTTP_ENCODING_STREAM_FLUSH_NONE': 'const'
    'HTTP_ENCODING_STREAM_FLUSH_SYNC': 'const'
    'HTTP_ENCODING_STREAM_FLUSH_FULL': 'const'
    'HTTP_E_RUNTIME': 'const'
    'HTTP_E_INVALID_PARAM': 'const'
    'HTTP_E_HEADER': 'const'
    'HTTP_E_MALFORMED_HEADERS': 'const'
    'HTTP_E_REQUEST_METHOD': 'const'
    'HTTP_E_MESSAGE_TYPE': 'const'
    'HTTP_E_ENCODING': 'const'
    'HTTP_E_REQUEST': 'const'
    'HTTP_E_REQUEST_POOL': 'const'
    'HTTP_E_SOCKET': 'const'
    'HTTP_E_RESPONSE': 'const'
    'HTTP_E_URL': 'const'
    'HTTP_E_QUERYSTRING': 'const'
    'HTTP_MSG_NONE': 'const'
    'HTTP_MSG_REQUEST': 'const'
    'HTTP_MSG_RESPONSE': 'const'
    'HTTP_QUERYSTRING_TYPE_BOOL': 'const'
    'HTTP_QUERYSTRING_TYPE_INT': 'const'
    'HTTP_QUERYSTRING_TYPE_FLOAT': 'const'
    'HTTP_QUERYSTRING_TYPE_STRING': 'const'
    'HTTP_QUERYSTRING_TYPE_ARRAY': 'const'
    'HTTP_QUERYSTRING_TYPE_OBJECT': 'const'
    'HTTP_AUTH_BASIC': 'const'
    'HTTP_AUTH_DIGEST': 'const'
    'HTTP_AUTH_NTLM': 'const'
    'HTTP_AUTH_GSSNEG': 'const'
    'HTTP_AUTH_ANY': 'const'
    'HTTP_VERSION_ANY': 'const'
    'HTTP_VERSION_1_0': 'const'
    'HTTP_VERSION_1_1': 'const'
    'HTTP_SSL_VERSION_ANY': 'const'
    'HTTP_SSL_VERSION_TLSv1': 'const'
    'HTTP_SSL_VERSION_SSLv3': 'const'
    'HTTP_SSL_VERSION_SSLv2': 'const'
    'HTTP_PROXY_SOCKS4': 'const'
    'HTTP_PROXY_SOCKS5': 'const'
    'HTTP_PROXY_HTTP': 'const'
    'HTTP_IPRESOLVE_V4': 'const'
    'HTTP_IPRESOLVE_V6': 'const'
    'HTTP_IPRESOLVE_ANY': 'const'
    'HTTP_METH_GET': 'const'
    'HTTP_METH_HEAD': 'const'
    'HTTP_METH_POST': 'const'
    'HTTP_METH_PUT': 'const'
    'HTTP_METH_DELETE': 'const'
    'HTTP_METH_OPTIONS': 'const'
    'HTTP_METH_TRACE': 'const'
    'HTTP_METH_CONNECT': 'const'
    'HTTP_METH_PROPFIND': 'const'
    'HTTP_METH_PROPPATCH': 'const'
    'HTTP_METH_MKCOL': 'const'
    'HTTP_METH_COPY': 'const'
    'HTTP_METH_MOVE': 'const'
    'HTTP_METH_LOCK': 'const'
    'HTTP_METH_UNLOCK': 'const'
    'HTTP_METH_VERSION_CONTROL': 'const'
    'HTTP_METH_REPORT': 'const'
    'HTTP_METH_CHECKOUT': 'const'
    'HTTP_METH_CHECKIN': 'const'
    'HTTP_METH_UNCHECKOUT': 'const'
    'HTTP_METH_MKWORKSPACE': 'const'
    'HTTP_METH_UPDATE': 'const'
    'HTTP_METH_LABEL': 'const'
    'HTTP_METH_MERGE': 'const'
    'HTTP_METH_BASELINE_CONTROL': 'const'
    'HTTP_METH_MKACTIVITY': 'const'
    'HTTP_METH_ACL': 'const'
    'HTTP_REDIRECT': 'const'
    'HTTP_REDIRECT_PERM': 'const'
    'HTTP_REDIRECT_FOUND': 'const'
    'HTTP_REDIRECT_POST': 'const'
    'HTTP_REDIRECT_PROXY': 'const'
    'HTTP_REDIRECT_TEMP': 'const'
    'HTTP_URL_REPLACE': 'const'
    'HTTP_URL_JOIN_PATH': 'const'
    'HTTP_URL_JOIN_QUERY': 'const'
    'HTTP_URL_STRIP_USER': 'const'
    'HTTP_URL_STRIP_PASS': 'const'
    'HTTP_URL_STRIP_AUTH': 'const'
    'HTTP_URL_STRIP_PORT': 'const'
    'HTTP_URL_STRIP_PATH': 'const'
    'HTTP_URL_STRIP_QUERY': 'const'
    'HTTP_URL_STRIP_FRAGMENT': 'const'
    'HTTP_URL_STRIP_ALL': 'const'
    # HTTP functions
    'http_cache_etag': 'function'
    'http_cache_last_modified': 'function'
    'http_chunked_decode': 'function'
    'http_deflate': 'function'
    'http_inflate': 'function'
    'http_build_cookie': 'function'
    'http_date': 'function'
    'http_get_request_body_stream': 'function'
    'http_get_request_body': 'function'
    'http_get_request_headers': 'function'
    'http_match_etag': 'function'
    'http_match_modified': 'function'
    'http_match_request_header': 'function'
    'http_support': 'function'
    'http_negotiate_charset': 'function'
    'http_negotiate_content_type': 'function'
    'http_negotiate_language': 'function'
    'ob_deflatehandler': 'function'
    'ob_etaghandler': 'function'
    'ob_inflatehandler': 'function'
    'http_parse_cookie': 'function'
    'http_parse_headers': 'function'
    'http_parse_message': 'function'
    'http_parse_params': 'function'
    'http_persistent_handles_clean': 'function'
    'http_persistent_handles_count': 'function'
    'http_persistent_handles_ident': 'function'
    'http_get': 'function'
    'http_head': 'function'
    'http_post_data': 'function'
    'http_post_fields': 'function'
    'http_put_data': 'function'
    'http_put_file': 'function'
    'http_put_stream': 'function'
    'http_request_body_encode': 'function'
    'http_request_method_exists': 'function'
    'http_request_method_name': 'function'
    'http_request_method_register': 'function'
    'http_request_method_unregister': 'function'
    'http_request': 'function'
    'http_redirect': 'function'
    'http_send_content_disposition': 'function'
    'http_send_content_type': 'function'
    'http_send_data': 'function'
    'http_send_file': 'function'
    'http_send_last_modified': 'function'
    'http_send_status': 'function'
    'http_send_stream': 'function'
    'http_throttle': 'function'
    'http_build_str': 'function'
    'http_build_url': 'function'

    # Sockets
    # Sockets constants
    'AF_UNIX': 'const'
    'AF_INET': 'const'
    'AF_INET6': 'const'
    'SOCK_STREAM': 'const'
    'SOCK_DGRAM': 'const'
    'SOCK_RAW': 'const'
    'SOCK_SEQPACKET': 'const'
    'SOCK_RDM': 'const'
    'MSG_OOB': 'const'
    'MSG_WAITALL': 'const'
    'MSG_PEEK': 'const'
    'MSG_DONTROUTE': 'const'
    'SO_DEBUG': 'const'
    'SO_REUSEADDR': 'const'
    'SO_KEEPALIVE': 'const'
    'SO_DONTROUTE': 'const'
    'SO_LINGER': 'const'
    'SO_BROADCAST': 'const'
    'SO_OOBINLINE': 'const'
    'SO_SNDBUF': 'const'
    'SO_RCVBUF': 'const'
    'SO_SNDLOWAT': 'const'
    'SO_RCVLOWAT': 'const'
    'SO_SNDTIMEO': 'const'
    'SO_RCVTIMEO': 'const'
    'SO_TYPE': 'const'
    'SO_ERROR': 'const'
    'SOL_SOCKET': 'const'
    'SOMAXCONN': 'const'
    'TCP_NODELAY': 'const'
    'PHP_NORMAL_READ': 'const'
    'PHP_BINARY_READ': 'const'
    'SOCKET_EINTR': 'const'
    'SOCKET_EBADF': 'const'
    'SOCKET_EACCES': 'const'
    'SOCKET_EFAULT': 'const'
    'SOCKET_EINVAL': 'const'
    'SOCKET_EMFILE': 'const'
    'SOCKET_EWOULDBLOCK': 'const'
    'SOCKET_EINPROGRESS': 'const'
    'SOCKET_EALREADY': 'const'
    'SOCKET_ENOTSOCK': 'const'
    'SOCKET_EDESTADDRREQ': 'const'
    'SOCKET_EMSGSIZE': 'const'
    'SOCKET_EPROTOTYPE': 'const'
    'SOCKET_ENOPROTOOPT': 'const'
    'SOCKET_EPROTONOSUPPORT': 'const'
    'SOCKET_ESOCKTNOSUPPORT': 'const'
    'SOCKET_EOPNOTSUPP': 'const'
    'SOCKET_EPFNOSUPPORT': 'const'
    'SOCKET_EAFNOSUPPORT': 'const'
    'SOCKET_EADDRINUSE': 'const'
    'SOCKET_EADDRNOTAVAIL': 'const'
    'SOCKET_ENETDOWN': 'const'
    'SOCKET_ENETUNREACH': 'const'
    'SOCKET_ENETRESET': 'const'
    'SOCKET_ECONNABORTED': 'const'
    'SOCKET_ECONNRESET': 'const'
    'SOCKET_ENOBUFS': 'const'
    'SOCKET_EISCONN': 'const'
    'SOCKET_ENOTCONN': 'const'
    'SOCKET_ESHUTDOWN': 'const'
    'SOCKET_ETOOMANYREFS': 'const'
    'SOCKET_ETIMEDOUT': 'const'
    'SOCKET_ECONNREFUSED': 'const'
    'SOCKET_ELOOP': 'const'
    'SOCKET_ENAMETOOLONG': 'const'
    'SOCKET_EHOSTDOWN': 'const'
    'SOCKET_EHOSTUNREACH': 'const'
    'SOCKET_ENOTEMPTY': 'const'
    'SOCKET_EPROCLIM': 'const'
    'SOCKET_EUSERS': 'const'
    'SOCKET_EDQUOT': 'const'
    'SOCKET_ESTALE': 'const'
    'SOCKET_EREMOTE': 'const'
    'SOCKET_EDISCON': 'const'
    'SOCKET_SYSNOTREADY': 'const'
    'SOCKET_VERNOTSUPPORTED': 'const'
    'SOCKET_NOTINITIALISED': 'const'
    'SOCKET_HOST_NOT_FOUND': 'const'
    'SOCKET_TRY_AGAIN': 'const'
    'SOCKET_NO_RECOVERY': 'const'
    'SOCKET_NO_DATA': 'const'
    'SOCKET_NO_ADDRESS': 'const'
    'SOL_TCP': 'const'
    'SOL_UDP': 'const'
    # Sockets function
    'socket_accept': 'function'
    'socket_bind': 'function'
    'socket_clear_error': 'function'
    'socket_close': 'function'
    'socket_cmsg_space': 'function'
    'socket_connect': 'function'
    'socket_create_listen': 'function'
    'socket_create_pair': 'function'
    'socket_create': 'function'
    'socket_get_option': 'function'
    'socket_getpeername': 'function'
    'socket_getsockname': 'function'
    'socket_import_stream': 'function'
    'socket_last_error': 'function'
    'socket_listen': 'function'
    'socket_read': 'function'
    'socket_recv': 'function'
    'socket_recvfrom': 'function'
    'socket_recvmsg': 'function'
    'socket_select': 'function'
    'socket_send': 'function'
    'socket_sendmsg': 'function'
    'socket_sendto': 'function'
    'socket_set_block': 'function'
    'socket_set_nonblock': 'function'
    'socket_set_option': 'function'
    'socket_shutdown': 'function'
    'socket_strerror': 'function'
    'socket_write': 'function'

    # TCP
    # TCP functions
    'tcpwrap_check': 'function'
}